const express = require('express');
const multer = require('multer');
const fetch = require('node-fetch');
const pdfParse = require('pdf-parse');
const fs = require('fs');
const path = require('path');
const gdsPromptV1 = require('./gds-prompt-v1');
const { buildPrototypeFiles: buildPrototypeFilesV1 } = require('./generator-v1');
const contentReviewPrompt = require('./content-review-prompt');
const gdsPromptV2 = require('./gds-prompt-v2');
const { buildPrototypeFiles: buildPrototypeFilesV2 } = require('./generator-v2');

const app = express();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 } });

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// ─── GitHub helpers ───────────────────────────────────────────────────────────

async function createGitHubRepo(repoName, token) {
  const res = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers: {
      'Authorization': `token ${token}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      name: repoName,
      private: false,
      auto_init: false,
      description: 'GOV.UK prototype generated by Prototype Engine'
    })
  });
  if (!res.ok) {
    const err = await res.json();
    throw new Error(`GitHub repo creation failed: ${err.message}`);
  }
  return await res.json();
}

async function pushFileToGitHub(owner, repo, filePath, content, token) {
  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`, {
    method: 'PUT',
    headers: {
      'Authorization': `token ${token}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      message: `Add ${filePath}`,
      content: Buffer.from(content).toString('base64')
    })
  });
  if (!res.ok) {
    const err = await res.json();
    throw new Error(`Failed to push ${filePath}: ${err.message}`);
  }
  return await res.json();
}

async function pushAllFiles(owner, repoName, files, token) {
  for (const [filePath, content] of Object.entries(files)) {
    await pushFileToGitHub(owner, repoName, filePath, content, token);
    await new Promise(r => setTimeout(r, 200));
  }
}

// ─── Render helpers ───────────────────────────────────────────────────────────

async function createRenderService(repoUrl, serviceName, renderApiKey, ownerId) {
  const res = await fetch('https://api.render.com/v1/services', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${renderApiKey}`,
      'Content-Type': 'application/json',
      'Accept': 'application/json'
    },
    body: JSON.stringify({
      type: 'web_service',
      name: serviceName,
      ownerId: ownerId,
      repo: repoUrl,
      branch: 'main',
      autoDeploy: 'yes',
      serviceDetails: {
        env: 'node',
        buildCommand: 'npm install',
        startCommand: 'npm start',
        plan: 'free',
        region: 'oregon',
        envSpecificDetails: {
          buildCommand: 'npm install',
          startCommand: 'npm start'
        }
      }
    })
  });
  if (!res.ok) {
    const err = await res.json();
    throw new Error(`Render service creation failed: ${JSON.stringify(err)}`);
  }
  return await res.json();
}

async function pollUntilLive(protoUrl, maxWaitMs = 300000) {
  const start = Date.now();
  while (Date.now() - start < maxWaitMs) {
    await new Promise(r => setTimeout(r, 15000));
    try {
      const res = await fetch(protoUrl, { timeout: 10000 });
      if (res.ok || res.status === 302 || res.status === 301) return true;
    } catch (e) {
      // still deploying
    }
  }
  throw new Error('Prototype took too long to deploy. Try opening the link in a minute.');
}

// ─── Prototype log helpers ────────────────────────────────────────────────────

const LOG_REPO = 'proto-engine-0x';
const LOG_FILE = 'prototypes-log.json';

async function appendToLog(entry, owner, token) {
  let existingLog = [];
  let sha = null;
  try {
    const res = await fetch(`https://api.github.com/repos/${owner}/${LOG_REPO}/contents/${LOG_FILE}`, {
      headers: { 'Authorization': `token ${token}`, 'Accept': 'application/vnd.github.v3+json' }
    });
    if (res.ok) {
      const data = await res.json();
      sha = data.sha;
      existingLog = JSON.parse(Buffer.from(data.content, 'base64').toString('utf8'));
    }
  } catch (e) {}

  existingLog.unshift(entry);
  if (existingLog.length > 200) existingLog = existingLog.slice(0, 200);

  const body = {
    message: `Log prototype: ${entry.serviceName}`,
    content: Buffer.from(JSON.stringify(existingLog, null, 2)).toString('base64')
  };
  if (sha) body.sha = sha;

  await fetch(`https://api.github.com/repos/${owner}/${LOG_REPO}/contents/${LOG_FILE}`, {
    method: 'PUT',
    headers: {
      'Authorization': `token ${token}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(body)
  });
}

async function getLog(owner, token) {
  try {
    const res = await fetch(`https://api.github.com/repos/${owner}/${LOG_REPO}/contents/${LOG_FILE}`, {
      headers: { 'Authorization': `token ${token}`, 'Accept': 'application/vnd.github.v3+json' }
    });
    if (!res.ok) return [];
    const data = await res.json();
    return JSON.parse(Buffer.from(data.content, 'base64').toString('utf8'));
  } catch (e) {
    return [];
  }
}

// ─── Launcher ─────────────────────────────────────────────────────────────────

app.get('/', (req, res) => {
  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Prototype Engine</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "GDS Transport", arial, sans-serif; background: #f8f8f8; min-height: 100vh; display: flex; flex-direction: column; -webkit-font-smoothing: antialiased; }
    main { max-width: 960px; margin: 0 auto; padding: 50px 30px 60px; flex: 1; width: 100%; }
    h1 { font-size: 48px; font-weight: 700; color: #0b0c0c; line-height: 1.1; margin-bottom: 8px; letter-spacing: -0.5px; }
    .lede { font-size: 19px; color: #505a5f; margin-bottom: 40px; line-height: 1.5; }
    .version-list { list-style: none; padding: 0; display: flex; flex-direction: column; gap: 12px; }
    .version-card { background: white; padding: 28px 30px; display: flex; align-items: center; justify-content: space-between; gap: 20px; border-radius: 10px; box-shadow: 0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04); border: 1px solid rgba(0,0,0,0.06); transition: box-shadow 0.2s ease, transform 0.2s ease; }
    .version-card:hover { box-shadow: 0 4px 12px rgba(0,0,0,0.08), 0 2px 4px rgba(0,0,0,0.04); transform: translateY(-1px); }
    .version-info { flex: 1; }
    .version-name { font-size: 22px; font-weight: 700; color: #0b0c0c; text-decoration: none; }
    .version-name:hover { color: #1d70b8; }
    .version-desc { font-size: 16px; color: #505a5f; margin-top: 6px; line-height: 1.5; }
    .badge { display: inline-block; font-size: 12px; font-weight: 700; padding: 4px 12px; text-transform: uppercase; letter-spacing: 0.8px; white-space: nowrap; border-radius: 20px; }
    .badge--stable { background: #e6f4ed; color: #00703c; }
    .badge--beta { background: #e8f1f8; color: #1d70b8; }
    .links-row { margin-top: 32px; display: flex; gap: 24px; flex-wrap: wrap; }
    .links-row a { font-size: 16px; color: #505a5f; text-decoration: none; transition: color 0.15s; }
    .links-row a:hover { color: #1d70b8; }
    .links-row a span { margin-right: 4px; }
    details { margin-top: 30px; font-size: 16px; color: #0b0c0c; }
    details summary { cursor: pointer; color: #1d70b8; font-size: 16px; list-style: none; display: flex; align-items: center; gap: 6px; }
    details summary::-webkit-details-marker { display: none; }
    details summary::before { content: ''; display: inline-block; width: 0; height: 0; border-left: 6px solid #1d70b8; border-top: 5px solid transparent; border-bottom: 5px solid transparent; transition: transform 0.15s ease; }
    details[open] summary::before { transform: rotate(90deg); }
    .details-body { padding: 20px 24px; background: white; border-radius: 8px; margin-top: 12px; box-shadow: 0 1px 3px rgba(0,0,0,0.04); border: 1px solid rgba(0,0,0,0.06); }
    .details-body p { font-size: 16px; margin-bottom: 15px; line-height: 1.6; color: #0b0c0c; }
    .details-body ul { font-size: 16px; line-height: 1.8; padding-left: 20px; color: #0b0c0c; }
    footer { background: #ffffff; padding: 24px 30px; color: #6f777b; font-size: 14px; text-align: center; border-top: 1px solid #e8e8e8; }
    @media (max-width: 768px) { h1 { font-size: 32px; } .version-card { flex-direction: column; align-items: flex-start; } }
    @keyframes pe-logo-in {
      0% { opacity:0; transform:scale(0.7) rotate(-8deg); }
      60% { transform:scale(1.08) rotate(2deg); }
      100% { opacity:1; transform:scale(1) rotate(0deg); }
    }
    .pe-logo { animation: pe-logo-in 0.5s cubic-bezier(0.34,1.56,0.64,1) both; }
  </style>
</head>
<body>
<header style="background:#e0531a;padding:14px 0;">
  <div style="max-width:960px;margin:0 auto;padding:0 30px;">
    <a href="/" style="text-decoration:none;display:inline-flex;align-items:center;gap:10px;">
      <svg class="pe-logo" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="0" y="0" width="11" height="11" fill="white"/>
        <rect x="13" y="0" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="0" y="13" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="13" y="13" width="11" height="11" fill="white"/>
      </svg>
      <span style="color:white;font-size:15px;font-weight:700;font-family:arial,sans-serif;letter-spacing:-0.3px;">Prototype Engine</span>
    </a>
  </div>
</header>
<main>
  <h1>Prototype Engine</h1>
  <p class="lede">Build a working GOV.UK prototype from a plain English brief.</p>
  <ul class="version-list">
    <li class="version-card">
      <div class="version-info">
        <a href="/v1" class="version-name">v1: Simple prototypes</a>
        <p class="version-desc">Linear question flows with validation, check-your-answers and confirmation pages.</p>
      </div>
      <span class="badge badge--stable">Stable</span>
    </li>
    <li class="version-card">
      <div class="version-info">
        <a href="/v2" class="version-name">v2: Branching prototypes</a>
        <p class="version-desc">Multi-path journeys with conditional routing and branching logic.</p>
      </div>
      <span class="badge badge--beta">Beta</span>
    </li>
  </ul>
  <div class="links-row">
    <a href="/prototypes"><span>&#8594;</span> All prototypes</a>
    <a href="/design-history"><span>&#8594;</span> Design history</a>
  </div>
  <details>
    <summary>Product roadmap</summary>
    <div class="details-body">
      <p>Each version adds new capabilities. We release one at a time, test for stability, then build the next.</p>
      <ul>
        <li>v1 — Simple linear prototypes (stable)</li>
        <li>v2 — Branching and conditional routing (beta)</li>
        <li>v3 — Additional GDS patterns: task lists, interruption cards, content pages (planned)</li>
      </ul>
    </div>
  </details>
</main>
<footer>Built on GOV.UK Prototype Kit v13 &middot; Powered by Claude</footer>
</body>
</html>`);
});

// ─── v1 Frontend ──────────────────────────────────────────────────────────────

app.get('/v1', (req, res) => {
  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Build a prototype – Prototype Engine</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "GDS Transport", arial, sans-serif; background: #f8f8f8; min-height: 100vh; display: flex; flex-direction: column; -webkit-font-smoothing: antialiased; }
    main { max-width: 960px; margin: 0 auto; padding: 50px 30px 60px; flex: 1; width: 100%; }

    h1 { font-size: 42px; font-weight: 700; color: #0b0c0c; line-height: 1.15; margin-bottom: 12px; letter-spacing: -0.5px; }
    .lede { font-size: 19px; color: #505a5f; margin-bottom: 36px; line-height: 1.5; }
    .form-card { background: white; border-radius: 12px; padding: 36px 32px 32px; box-shadow: 0 1px 4px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04); border: 1px solid rgba(0,0,0,0.06); }
    .form-group { margin-bottom: 28px; }
    label { display: block; font-size: 18px; font-weight: 700; color: #0b0c0c; margin-bottom: 6px; }
    .hint { font-size: 15px; color: #6f777b; margin-bottom: 8px; line-height: 1.4; }
    textarea, input[type="text"], input[type="url"] { width: 100%; padding: 12px 14px; font-size: 17px; font-family: inherit; border: 2px solid #b1b4b6; border-radius: 6px; background: white; color: #0b0c0c; transition: border-color 0.15s, box-shadow 0.15s; }
    textarea:hover, input[type="url"]:hover { border-color: #0b0c0c; }
    textarea:focus, input:focus { outline: none; border-color: #0b0c0c; box-shadow: 0 0 0 3px #ffdd00; }
    textarea { resize: vertical; min-height: 72px; }
    textarea::placeholder, input::placeholder { color: #b1b4b6; }
    .file-upload-label { display: inline-flex; align-items: center; gap: 8px; padding: 10px 16px; background: white; border: 2px solid #b1b4b6; border-radius: 6px; cursor: pointer; font-size: 15px; font-weight: 600; color: #0b0c0c; transition: border-color 0.15s, background 0.15s; }
    .file-upload-label:hover { border-color: #0b0c0c; background: #f8f8f8; }
    .file-name { font-size: 14px; color: #6f777b; margin-top: 8px; }
    input[type="file"] { display: none; }
    .generate-btn { background: #00703c; color: white; border: none; padding: 14px 24px; font-size: 18px; font-weight: 700; font-family: inherit; cursor: pointer; display: inline-flex; align-items: center; gap: 10px; border-radius: 6px; transition: background 0.15s, box-shadow 0.15s, transform 0.1s; box-shadow: 0 2px 4px rgba(0,112,60,0.2); }
    .generate-btn:hover { background: #005a30; box-shadow: 0 4px 8px rgba(0,112,60,0.25); transform: translateY(-1px); }
    .generate-btn:active { transform: translateY(0); box-shadow: 0 1px 2px rgba(0,112,60,0.2); }
    .generate-btn:focus { outline: 3px solid #ffdd00; outline-offset: 2px; }
    .generate-btn:disabled { background: #00703c; opacity: 0.7; cursor: wait; transform: none; box-shadow: none; }
    .btn-arrow { width: 18px; height: 18px; fill: white; }
    .form-footer { margin-top: 14px; font-size: 15px; color: #6f777b; }
    .form-footer a { color: #6f777b; transition: color 0.15s; }
    .form-footer a:hover { color: #1d70b8; }

    /* Checkbox */
    .checkbox-row { display: flex; align-items: flex-start; gap: 12px; padding: 16px 18px; background: #faf8fb; border: 1px solid #e8e0e8; border-radius: 8px; }
    .checkbox-row input[type="checkbox"] { width: 22px; height: 22px; margin: 2px 0 0; cursor: pointer; accent-color: #6f3764; flex-shrink: 0; }
    .checkbox-label { font-size: 17px; font-weight: 700; color: #0b0c0c; cursor: pointer; }
    .exp-badge { display: inline-block; margin-left: 8px; padding: 2px 8px; background: #6f3764; color: white; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.8px; border-radius: 3px; vertical-align: middle; }

    /* Progress panel */
    .progress-panel { display: none; margin-top: 24px; background: white; border: 1px solid rgba(0,0,0,0.06); border-radius: 12px; padding: 28px; box-shadow: 0 1px 4px rgba(0,0,0,0.06); }
    .progress-panel.visible { display: block; animation: slideIn 0.3s ease; }
    .progress-bar-track { background: #f0f0f0; height: 6px; margin-bottom: 24px; border-radius: 3px; overflow: hidden; }
    .progress-bar-fill { height: 6px; background: linear-gradient(90deg, #1d70b8, #2b8cc4); width: 0%; transition: width 0.8s cubic-bezier(0.4,0,0.2,1); border-radius: 3px; }
    .progress-bar-fill.complete { background: linear-gradient(90deg, #00703c, #28a745); }
    .progress-steps { list-style: none; padding: 0; }
    .progress-steps li { font-size: 15px; color: #b1b4b6; padding: 10px 0; display: flex; align-items: center; gap: 14px; border-bottom: 1px solid #f5f5f5; transition: color 0.2s; }
    .progress-steps li:last-child { border-bottom: none; }
    .progress-steps li.active { color: #0b0c0c; font-weight: 600; }
    .progress-steps li.done { color: #00703c; }
    .step-icon { width: 20px; height: 20px; text-align: center; font-size: 13px; flex-shrink: 0; display: flex; align-items: center; justify-content: center; border-radius: 50%; }
    .progress-steps li.active .step-icon { background: #e8f1f8; color: #1d70b8; font-size: 10px; }
    .progress-steps li.done .step-icon { background: #e6f4ed; color: #00703c; }

    /* Done panel */
    .done-panel { display: none; margin-top: 24px; background: white; border-radius: 12px; padding: 32px; box-shadow: 0 2px 8px rgba(0,112,60,0.1); border: 1px solid #c1e7d4; }
    .done-panel.visible { display: block; animation: slideIn 0.4s ease; }
    @keyframes slideIn { from { opacity: 0; transform: translateY(12px); } to { opacity: 1; transform: translateY(0); } }
    .done-header { display: flex; align-items: center; gap: 16px; margin-bottom: 12px; }
    .done-tick-circle { width: 44px; height: 44px; border-radius: 50%; background: #00703c; display: flex; align-items: center; justify-content: center; flex-shrink: 0; animation: popIn 0.4s cubic-bezier(0.34,1.56,0.64,1) both; }
    @keyframes popIn { from { transform: scale(0); } to { transform: scale(1); } }
    .done-tick-circle svg { width: 24px; height: 24px; fill: none; stroke: white; stroke-width: 3; stroke-linecap: round; stroke-linejoin: round; }
    .done-tick-circle svg path { stroke-dasharray: 40; stroke-dashoffset: 40; animation: drawTick 0.35s ease 0.3s forwards; }
    @keyframes drawTick { to { stroke-dashoffset: 0; } }
    .done-title { font-size: 24px; font-weight: 700; color: #0b0c0c; }
    .done-sub { font-size: 16px; color: #505a5f; margin-bottom: 20px; line-height: 1.5; }
    .open-proto-btn { display: inline-flex; align-items: center; gap: 8px; background: #1d70b8; color: white; padding: 13px 22px; font-size: 18px; font-weight: 700; font-family: inherit; text-decoration: none; border-radius: 6px; transition: background 0.15s, box-shadow 0.15s, transform 0.1s; box-shadow: 0 2px 4px rgba(29,112,184,0.2); }
    .open-proto-btn:hover { background: #003078; transform: translateY(-1px); box-shadow: 0 4px 8px rgba(29,112,184,0.25); }
    .truncated-notice { margin-top: 20px; padding: 14px 18px; background: #f8f8f8; border-radius: 8px; border: 1px solid #e8e8e8; font-size: 15px; color: #505a5f; line-height: 1.5; }

    /* Error panel */
    .error-panel { display: none; margin-top: 24px; background: white; border-radius: 12px; padding: 28px; box-shadow: 0 2px 8px rgba(212,53,28,0.08); border: 1px solid #f6d7d2; }
    .error-panel.visible { display: block; animation: slideIn 0.3s ease; }
    .error-title { font-size: 18px; font-weight: 700; color: #d4351c; margin-bottom: 8px; display: flex; align-items: center; gap: 10px; }
    .error-msg { font-size: 16px; color: #505a5f; line-height: 1.5; }

    /* Spinner */
    .spinner { display: inline-block; width: 16px; height: 16px; border: 2px solid rgba(255,255,255,0.4); border-top-color: white; border-radius: 50%; animation: spin 0.7s linear infinite; }
    @keyframes spin { to { transform: rotate(360deg); } }

    footer { background: #ffffff; padding: 24px 30px; color: #6f777b; font-size: 14px; text-align: center; border-top: 1px solid #e8e8e8; }
    @media (max-width: 768px) { h1 { font-size: 32px; } .form-card { padding: 24px 20px; } }
  </style>
</head>
<body>
<header style="background:#e0531a;padding:14px 0;">
  <div style="max-width:960px;margin:0 auto;padding:0 30px;">
    <a href="/" style="text-decoration:none;display:inline-flex;align-items:center;gap:10px;">
      <svg class="pe-logo" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="0" y="0" width="11" height="11" fill="white"/>
        <rect x="13" y="0" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="0" y="13" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="13" y="13" width="11" height="11" fill="white"/>
      </svg>
      <span style="color:white;font-size:15px;font-weight:700;font-family:arial,sans-serif;letter-spacing:-0.3px;">Prototype Engine</span>
    </a>
  </div>
</header>
<main>
<div style="max-width: 600px;">
    <div>
      <h1>Build a GOV.UK prototype</h1>
      <p class="lede">Describe your service and we'll generate a working prototype with GDS components, validation, and deployment.</p>
      <div class="form-card">
      <form id="generateForm" enctype="multipart/form-data">
        <div class="form-group">
          <label for="q1">Who are the users and what are their needs?</label>
          <textarea id="q1" name="q1" rows="3" placeholder="Parents applying for free school meals. They may be anxious and need to know quickly if they are eligible."></textarea>
        </div>
        <div class="form-group">
          <label for="q2">What does the service need to achieve?</label>
          <textarea id="q2" name="q2" rows="3" placeholder="Help parents apply quickly. If ineligible, signpost to other support rather than leaving them at a dead end."></textarea>
        </div>
        <div class="form-group">
          <label for="q3">What content principles should we apply?</label>
          <textarea id="q3" name="q3" rows="3" placeholder="Plain, warm and direct. No jargon. Use 'you' and 'your child' throughout."></textarea>
        </div>
        <div class="form-group">
          <label for="pdf">Upload a PDF (optional)</label>
          <p class="hint">Policy documents, existing service specs, research findings.</p>
          <label class="file-upload-label" for="pdf">
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M8 1v10M4 5l4-4 4 4" stroke="#0b0c0c" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M1 11v3h14v-3" stroke="#0b0c0c" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>
            Choose file
          </label>
          <input type="file" id="pdf" name="pdf" accept=".pdf">
          <div class="file-name" id="fileName">No file chosen</div>
        </div>
        <div class="form-group">
          <label for="url">Reference URL (optional)</label>
          <p class="hint">A live service or document to reference.</p>
          <input type="url" id="url" name="url" placeholder="https://www.gov.uk/example">
        </div>
        <div class="form-group">
          <div class="checkbox-row">
            <input type="checkbox" id="contentReview" name="contentReview" value="true">
            <div>
              <label for="contentReview" class="checkbox-label">Apply content review</label>
              <span class="exp-badge">Experimental</span>
              <p class="hint" style="margin-top: 6px; margin-bottom: 0;">Improves question wording, hints, and error messages using GDS content design rules.</p>
            </div>
          </div>
        </div>
        <button type="submit" class="generate-btn" id="generateBtn">
          <span id="btnText">Generate prototype</span>
          <svg class="btn-arrow" id="btnArrow" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60">
            <path d="M0 20h40l-8-8 4-4 16 16-16 16-4-4 8-8H0z"/>
          </svg>
        </button>
        <p class="form-footer">or <a href="/prototypes">view previously generated prototypes</a></p>
      </form>
      </div>

      <!-- Progress panel -->
      <div class="progress-panel" id="progressPanel">
        <div class="progress-bar-track">
          <div class="progress-bar-fill" id="progressBar"></div>
        </div>
        <ul class="progress-steps">
          <li id="step-pdf" style="display:none;"><span class="step-icon" id="icon-pdf">–</span> Reading document</li>
          <li id="step-claude"><span class="step-icon" id="icon-claude">–</span> Generating with Claude</li>
          <li id="step-github"><span class="step-icon" id="icon-github">–</span> Pushing to GitHub</li>
          <li id="step-render"><span class="step-icon" id="icon-render">–</span> Creating Render service</li>
          <li id="step-deploy"><span class="step-icon" id="icon-deploy">–</span> Waiting for prototype to go live</li>
        </ul>
      </div>

      <!-- Done panel -->
      <div class="done-panel" id="donePanel">
        <div class="done-header">
          <div class="done-tick-circle">
            <svg viewBox="0 0 24 24"><path d="M4 12l5 5L20 7"/></svg>
          </div>
          <div class="done-title">Your prototype is live</div>
        </div>
        <p class="done-sub">It is ready to use. Share the link with your team.</p>
        <a href="#" id="openProtoBtn" class="open-proto-btn" target="_blank" rel="noopener">Open prototype &#8594;</a>
        <div id="pdfTruncatedNotice" class="truncated-notice" style="display:none;">Your document was long so we summarised the most relevant parts. The prototype is based on that summary.</div>
      </div>

      <!-- Error panel -->
      <div class="error-panel" id="errorPanel">
        <div class="error-title">Something went wrong</div>
        <div class="error-msg" id="errorMsg"></div>
      </div>
    </div>

  </div>
</main>
<footer>Built on GOV.UK Prototype Kit v13 &middot; Powered by Claude</footer>

<script>
  document.getElementById('pdf').addEventListener('change', function() {
    document.getElementById('fileName').textContent = this.files[0] ? this.files[0].name : 'No file chosen';
  });

  // Step state helpers
  function setStep(stepId, iconId, state) {
    const li = document.getElementById(stepId);
    const icon = document.getElementById(iconId);
    li.className = state;
    if (state === 'active') icon.textContent = '●';
    else if (state === 'done') icon.textContent = '✓';
    else icon.textContent = '–';
  }

  // Timed fake progress that advances through steps on a schedule
  // Real done only fires when server responds
  let progressTimer = null;

  function startFakeProgress(hasPdf) {
    const bar = document.getElementById('progressBar');
    const pdfStep = document.getElementById('step-pdf');
    let steps;

    if (hasPdf) {
      pdfStep.style.display = '';
      steps = [
        { stepId: 'step-pdf',     iconId: 'icon-pdf',     delay: 0,     pct: 10 },
        { stepId: 'step-claude',  iconId: 'icon-claude',  delay: 12000, pct: 25 },
        { stepId: 'step-github',  iconId: 'icon-github',  delay: 24000, pct: 50 },
        { stepId: 'step-render',  iconId: 'icon-render',  delay: 36000, pct: 65 },
        { stepId: 'step-deploy',  iconId: 'icon-deploy',  delay: 50000, pct: 80 }
      ];
    } else {
      pdfStep.style.display = 'none';
      steps = [
        { stepId: 'step-claude',  iconId: 'icon-claude',  delay: 0,     pct: 15 },
        { stepId: 'step-github',  iconId: 'icon-github',  delay: 18000, pct: 45 },
        { stepId: 'step-render',  iconId: 'icon-render',  delay: 30000, pct: 65 },
        { stepId: 'step-deploy',  iconId: 'icon-deploy',  delay: 45000, pct: 80 }
      ];
    }

    let prevStepId = null, prevIconId = null;
    steps.forEach(function(s) {
      const t = setTimeout(function() {
        if (prevStepId) setStep(prevStepId, prevIconId, 'done');
        setStep(s.stepId, s.iconId, 'active');
        bar.style.width = s.pct + '%';
        prevStepId = s.stepId;
        prevIconId = s.iconId;
      }, s.delay);
      if (!progressTimer) progressTimer = [];
      progressTimer.push(t);
    });
  }

  function stopFakeProgress() {
    if (progressTimer) progressTimer.forEach(clearTimeout);
    progressTimer = null;
  }

  document.getElementById('generateForm').addEventListener('submit', async function(e) {
    e.preventDefault();

    const btn = document.getElementById('generateBtn');
    const btnText = document.getElementById('btnText');
    const btnArrow = document.getElementById('btnArrow');
    const progressPanel = document.getElementById('progressPanel');
    const donePanel = document.getElementById('donePanel');
    const errorPanel = document.getElementById('errorPanel');
    const bar = document.getElementById('progressBar');
    const hasPdf = document.getElementById('pdf').files.length > 0;

    // Reset UI
    donePanel.className = 'done-panel';
    errorPanel.className = 'error-panel';
    document.getElementById('pdfTruncatedNotice').style.display = 'none';
    progressPanel.className = 'progress-panel visible';
    bar.style.width = '5%';
    bar.className = 'progress-bar-fill';
    var allSteps = ['step-claude','step-github','step-render','step-deploy'];
    if (hasPdf) allSteps.unshift('step-pdf');
    allSteps.forEach(function(id) {
      document.getElementById(id).className = '';
      var iconId = 'icon-' + id.replace('step-', '');
      document.getElementById(iconId).textContent = '–';
    });

    btn.disabled = true;
    btnArrow.style.display = 'none';
    btnText.innerHTML = '<span class="spinner"></span> Generating&hellip;';

    startFakeProgress(hasPdf);

    try {
      const formData = new FormData(this);
      const response = await fetch('/generate-v1', { method: 'POST', body: formData });

      stopFakeProgress();

      if (!response.ok) {
        const err = await response.json().catch(function() { return { error: 'Unknown error' }; });
        throw new Error(err.error || 'Something went wrong');
      }

      const result = await response.json();

      // All steps done
      bar.style.width = '100%';
      bar.className = 'progress-bar-fill complete';
      var doneSteps = ['step-claude','step-github','step-render','step-deploy'];
      if (hasPdf) doneSteps.unshift('step-pdf');
      doneSteps.forEach(function(id) {
        setStep(id, 'icon-' + id.replace('step-', ''), 'done');
      });

      // Show done panel
      progressPanel.className = 'progress-panel';
      document.getElementById('openProtoBtn').href = result.url;
      donePanel.className = 'done-panel visible';

      // Show truncation notice if applicable
      if (result.pdfTruncated) {
        document.getElementById('pdfTruncatedNotice').style.display = 'block';
      }

    } catch (err) {
      stopFakeProgress();
      progressPanel.className = 'progress-panel';
      document.getElementById('errorMsg').textContent = err.message || 'Try again or simplify your brief.';
      errorPanel.className = 'error-panel visible';
    }

    btn.disabled = false;
    btnArrow.style.display = '';
    btnText.textContent = 'Generate prototype';
  });
</script>
</body>
</html>`);
});

// ─── v1 Generate endpoint ─────────────────────────────────────────────────────

app.post('/generate-v1', upload.single('pdf'), async (req, res) => {
  try {
    const { q1, q2, q3, url } = req.body;
    const brief = [q1, q2, q3].filter(Boolean).map((s, i) => {
      const labels = ['Users and needs', 'Service goals', 'Content principles'];
      return labels[i] + ': ' + s.trim();
    }).join('\n\n');
    const apiKey = process.env.ANTHROPIC_API_KEY;
    const githubToken = process.env.GITHUB_TOKEN;
    const renderApiKey = process.env.RENDER_API_KEY;
    const renderOwnerId = process.env.RENDER_OWNER_ID;
    const githubUsername = process.env.GITHUB_USERNAME;

    if (!apiKey) return res.status(500).json({ error: 'ANTHROPIC_API_KEY not set' });
    if (!githubToken) return res.status(500).json({ error: 'GITHUB_TOKEN not set' });
    if (!renderApiKey) return res.status(500).json({ error: 'RENDER_API_KEY not set' });
    if (!renderOwnerId) return res.status(500).json({ error: 'RENDER_OWNER_ID not set' });
    if (!githubUsername) return res.status(500).json({ error: 'GITHUB_USERNAME not set' });
    if (!q1 || q1.trim().length < 5) return res.status(400).json({ error: 'Tell us who the users are and what they need' });

    // Step 1: PDF summarisation
    let pdfSummary = null;
    let pdfTruncated = false;
    if (req.file) {
      try {
        const pdfData = await pdfParse(req.file.buffer);
        let pdfText = pdfData.text;
        if (pdfText.length > 15000) {
          if (pdfText.length > 80000) {
            pdfText = pdfText.slice(0, 80000);
            pdfTruncated = true;
          }
          try {
            const summaryResponse = await fetch('https://api.anthropic.com/v1/messages', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'x-api-key': apiKey,
                'anthropic-version': '2023-06-01'
              },
              body: JSON.stringify({
                model: 'claude-sonnet-4-20250514',
                max_tokens: 2000,
                system: 'You are a government policy analyst. You will receive a service brief and a policy document. Extract and summarise only the content relevant to the brief. Return a clean markdown summary covering: eligibility rules and criteria, evidence requirements, key process steps and timeframes, any user-facing terminology that must be used, and any exclusions or special cases. Be concise. Maximum 1500 words.',
                messages: [{ role: 'user', content: `Brief: ${brief.trim()}\n\nDocument:\n${pdfText}` }]
              })
            });
            if (summaryResponse.ok) {
              const summaryData = await summaryResponse.json();
              pdfSummary = summaryData.content[0].text.trim();
            }
          } catch (e) {
            console.error('PDF summarisation failed, continuing without summary:', e.message);
          }
        } else {
          pdfSummary = pdfText;
        }
      } catch (e) {
        console.error('PDF parsing failed:', e.message);
      }
    }

    // Step 2: Claude generation
    let userMessage = `Brief: ${brief.trim()}`;
    if (pdfSummary) {
      userMessage += `\n\nPolicy document summary — use this to inform eligibility rules, question wording, hints, confirmation content, and any guidance:\n${pdfSummary}`;
    }
    if (url && url.trim()) userMessage += `\n\nReference URL: ${url.trim()}`;
    userMessage += '\n\nReturn only the JSON object. No explanation. No markdown.';

    const claudeResponse = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 4000,
        system: gdsPromptV1,
        messages: [{ role: 'user', content: userMessage }]
      })
    });

    if (!claudeResponse.ok) {
      const err = await claudeResponse.json();
      throw new Error(err.error?.message || 'Claude API error');
    }

    const claudeData = await claudeResponse.json();
    const rawText = claudeData.content[0].text.trim();

    let spec;
    try {
      const clean = rawText.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/```\s*$/i, '').trim();
      spec = JSON.parse(clean);
    } catch (e) {
      throw new Error('Claude returned invalid JSON. Try simplifying your brief.');
    }

    if (!spec.serviceName || !spec.questions || spec.questions.length < 1) {
      throw new Error('Prototype spec incomplete. Try again.');
    }

    // Optional content review pass
    if (req.body.contentReview === 'true') {
      try {
        const reviewResponse = await fetch('https://api.anthropic.com/v1/messages', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'x-api-key': apiKey,
            'anthropic-version': '2023-06-01'
          },
          body: JSON.stringify({
            model: 'claude-sonnet-4-20250514',
            max_tokens: 2000,
            system: contentReviewPrompt,
            messages: [{ role: 'user', content: JSON.stringify(spec) + '\n\nReturn only the improved JSON object. No explanation. No markdown.' }]
          })
        });

        if (reviewResponse.ok) {
          const reviewData = await reviewResponse.json();
          const reviewText = reviewData.content[0].text.trim();
          const cleanReview = reviewText.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/```\s*$/i, '').trim();
          spec = JSON.parse(cleanReview);
        }
      } catch (e) {
        console.error('Content review pass failed, continuing with original spec:', e.message);
      }
    }

    // Step 2: Build and push to GitHub
    const files = buildPrototypeFilesV1(spec);
    const timestamp = Date.now();
    const repoName = `prototype-${timestamp}`;

    await createGitHubRepo(repoName, githubToken);
    await pushAllFiles(githubUsername, repoName, files, githubToken);

    const repoUrl = `https://github.com/${githubUsername}/${repoName}`;

    // Step 3: Create Render service
    const serviceName = `prototype-${timestamp}`;
    const renderData = await createRenderService(repoUrl, serviceName, renderApiKey, renderOwnerId);

    const serviceId = renderData.service?.id;
    if (!serviceId) throw new Error('Render did not return a service ID');

    // Step 4: Poll until actually live
    const protoUrl = `https://${serviceName}.onrender.com`;
    await pollUntilLive(protoUrl);
    await new Promise(r => setTimeout(r, 20000));

    // Log it (fire and forget)
    appendToLog({
      serviceName: spec.serviceName,
      brief: brief.trim().slice(0, 120),
      url: protoUrl,
      repoUrl,
      createdAt: new Date().toISOString()
    }, githubUsername, githubToken).catch(e => console.error('Log write failed:', e));

    res.json({ url: protoUrl, repoUrl, pdfTruncated });

  } catch (err) {
    console.error(err);
    if (!res.headersSent) res.status(500).json({ error: err.message });
  }
});

// ─── v2 Frontend ──────────────────────────────────────────────────────────────

app.get('/v2', (req, res) => {
  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Branching Prototypes – Prototype Engine</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "GDS Transport", arial, sans-serif; background: #f8f8f8; min-height: 100vh; display: flex; flex-direction: column; -webkit-font-smoothing: antialiased; }
    main { max-width: 960px; margin: 0 auto; padding: 50px 30px 60px; flex: 1; width: 100%; }

    h1 { font-size: 42px; font-weight: 700; color: #0b0c0c; line-height: 1.15; margin-bottom: 12px; letter-spacing: -0.5px; }
    .lede { font-size: 19px; color: #505a5f; margin-bottom: 36px; line-height: 1.5; }
    .form-card { background: white; border-radius: 12px; padding: 36px 32px 32px; box-shadow: 0 1px 4px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04); border: 1px solid rgba(0,0,0,0.06); }
    .form-group { margin-bottom: 28px; }
    label { display: block; font-size: 18px; font-weight: 700; color: #0b0c0c; margin-bottom: 6px; }
    .hint { font-size: 15px; color: #6f777b; margin-bottom: 8px; line-height: 1.4; }
    textarea, input[type="text"], input[type="url"] { width: 100%; padding: 12px 14px; font-size: 17px; font-family: inherit; border: 2px solid #b1b4b6; border-radius: 6px; background: white; color: #0b0c0c; transition: border-color 0.15s, box-shadow 0.15s; }
    textarea:hover, input[type="url"]:hover { border-color: #0b0c0c; }
    textarea:focus, input:focus { outline: none; border-color: #0b0c0c; box-shadow: 0 0 0 3px #ffdd00; }
    textarea { resize: vertical; min-height: 72px; }
    textarea::placeholder, input::placeholder { color: #b1b4b6; }
    .file-upload-label { display: inline-flex; align-items: center; gap: 8px; padding: 10px 16px; background: white; border: 2px solid #b1b4b6; border-radius: 6px; cursor: pointer; font-size: 15px; font-weight: 600; color: #0b0c0c; transition: border-color 0.15s, background 0.15s; }
    .file-upload-label:hover { border-color: #0b0c0c; background: #f8f8f8; }
    .file-name { font-size: 14px; color: #6f777b; margin-top: 8px; }
    input[type="file"] { display: none; }
    .generate-btn { background: #00703c; color: white; border: none; padding: 14px 24px; font-size: 18px; font-weight: 700; font-family: inherit; cursor: pointer; display: inline-flex; align-items: center; gap: 10px; border-radius: 6px; transition: background 0.15s, box-shadow 0.15s, transform 0.1s; box-shadow: 0 2px 4px rgba(0,112,60,0.2); }
    .generate-btn:hover { background: #005a30; box-shadow: 0 4px 8px rgba(0,112,60,0.25); transform: translateY(-1px); }
    .generate-btn:active { transform: translateY(0); box-shadow: 0 1px 2px rgba(0,112,60,0.2); }
    .generate-btn:focus { outline: 3px solid #ffdd00; outline-offset: 2px; }
    .generate-btn:disabled { background: #00703c; opacity: 0.7; cursor: wait; transform: none; box-shadow: none; }
    .btn-arrow { width: 18px; height: 18px; fill: white; }
    .form-footer { margin-top: 14px; font-size: 15px; color: #6f777b; }
    .form-footer a { color: #6f777b; transition: color 0.15s; }
    .form-footer a:hover { color: #1d70b8; }

    /* Progress panel */
    .progress-panel { display: none; margin-top: 24px; background: white; border: 1px solid rgba(0,0,0,0.06); border-radius: 12px; padding: 28px; box-shadow: 0 1px 4px rgba(0,0,0,0.06); }
    .progress-panel.visible { display: block; animation: slideIn 0.3s ease; }
    .progress-bar-track { background: #f0f0f0; height: 6px; margin-bottom: 24px; border-radius: 3px; overflow: hidden; }
    .progress-bar-fill { height: 6px; background: linear-gradient(90deg, #1d70b8, #2b8cc4); width: 0%; transition: width 0.8s cubic-bezier(0.4,0,0.2,1); border-radius: 3px; }
    .progress-bar-fill.complete { background: linear-gradient(90deg, #00703c, #28a745); }
    .progress-steps { list-style: none; padding: 0; }
    .progress-steps li { font-size: 15px; color: #b1b4b6; padding: 10px 0; display: flex; align-items: center; gap: 14px; border-bottom: 1px solid #f5f5f5; transition: color 0.2s; }
    .progress-steps li:last-child { border-bottom: none; }
    .progress-steps li.active { color: #0b0c0c; font-weight: 600; }
    .progress-steps li.done { color: #00703c; }
    .step-icon { width: 20px; height: 20px; text-align: center; font-size: 13px; flex-shrink: 0; display: flex; align-items: center; justify-content: center; border-radius: 50%; }
    .progress-steps li.active .step-icon { background: #e8f1f8; color: #1d70b8; font-size: 10px; }
    .progress-steps li.done .step-icon { background: #e6f4ed; color: #00703c; }

    /* Done panel */
    .done-panel { display: none; margin-top: 24px; background: white; border-radius: 12px; padding: 32px; box-shadow: 0 2px 8px rgba(0,112,60,0.1); border: 1px solid #c1e7d4; }
    .done-panel.visible { display: block; animation: slideIn 0.4s ease; }
    @keyframes slideIn { from { opacity: 0; transform: translateY(12px); } to { opacity: 1; transform: translateY(0); } }
    .done-header { display: flex; align-items: center; gap: 16px; margin-bottom: 12px; }
    .done-tick-circle { width: 44px; height: 44px; border-radius: 50%; background: #00703c; display: flex; align-items: center; justify-content: center; flex-shrink: 0; animation: popIn 0.4s cubic-bezier(0.34,1.56,0.64,1) both; }
    @keyframes popIn { from { transform: scale(0); } to { transform: scale(1); } }
    .done-tick-circle svg { width: 24px; height: 24px; fill: none; stroke: white; stroke-width: 3; stroke-linecap: round; stroke-linejoin: round; }
    .done-tick-circle svg path { stroke-dasharray: 40; stroke-dashoffset: 40; animation: drawTick 0.35s ease 0.3s forwards; }
    @keyframes drawTick { to { stroke-dashoffset: 0; } }
    .done-title { font-size: 24px; font-weight: 700; color: #0b0c0c; }
    .done-sub { font-size: 16px; color: #505a5f; margin-bottom: 20px; line-height: 1.5; }
    .open-proto-btn { display: inline-flex; align-items: center; gap: 8px; background: #1d70b8; color: white; padding: 13px 22px; font-size: 18px; font-weight: 700; font-family: inherit; text-decoration: none; border-radius: 6px; transition: background 0.15s, box-shadow 0.15s, transform 0.1s; box-shadow: 0 2px 4px rgba(29,112,184,0.2); }
    .open-proto-btn:hover { background: #003078; transform: translateY(-1px); box-shadow: 0 4px 8px rgba(29,112,184,0.25); }
    .truncated-notice { margin-top: 20px; padding: 14px 18px; background: #f8f8f8; border-radius: 8px; border: 1px solid #e8e8e8; font-size: 15px; color: #505a5f; line-height: 1.5; }

    /* Error panel */
    .error-panel { display: none; margin-top: 24px; background: white; border-radius: 12px; padding: 28px; box-shadow: 0 2px 8px rgba(212,53,28,0.08); border: 1px solid #f6d7d2; }
    .error-panel.visible { display: block; animation: slideIn 0.3s ease; }
    .error-title { font-size: 18px; font-weight: 700; color: #d4351c; margin-bottom: 8px; }
    .error-msg { font-size: 16px; color: #505a5f; line-height: 1.5; }

    /* Spinner */
    .spinner { display: inline-block; width: 16px; height: 16px; border: 2px solid rgba(255,255,255,0.4); border-top-color: white; border-radius: 50%; animation: spin 0.7s linear infinite; }
    @keyframes spin { to { transform: rotate(360deg); } }

    footer { background: #ffffff; padding: 24px 30px; color: #6f777b; font-size: 14px; text-align: center; border-top: 1px solid #e8e8e8; }
    @media (max-width: 768px) { h1 { font-size: 32px; } .form-card { padding: 24px 20px; } }
  </style>
</head>
<body>
<header style="background:#e0531a;padding:14px 0;">
  <div style="max-width:960px;margin:0 auto;padding:0 30px;">
    <a href="/" style="text-decoration:none;display:inline-flex;align-items:center;gap:10px;">
      <svg class="pe-logo" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="0" y="0" width="11" height="11" fill="white"/>
        <rect x="13" y="0" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="0" y="13" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="13" y="13" width="11" height="11" fill="white"/>
      </svg>
      <span style="color:white;font-size:15px;font-weight:700;font-family:arial,sans-serif;letter-spacing:-0.3px;">Prototype Engine</span>
    </a>
  </div>
</header>
<main>
<div style="max-width: 600px;">
    <div>
      <h1>Build a branching prototype</h1>
      <p class="lede">Describe your service and we'll generate a working prototype with conditional branching, GDS components, and deployment.</p>
      <div class="form-card">
      <form id="generateForm" enctype="multipart/form-data">
        <div class="form-group">
          <label for="q1">Who are the users and what are their needs?</label>
          <textarea id="q1" name="q1" rows="3" placeholder="Parents applying for free school meals. They may be anxious and need to know quickly if they are eligible."></textarea>
        </div>
        <div class="form-group">
          <label for="q2">What does the service need to achieve?</label>
          <textarea id="q2" name="q2" rows="3" placeholder="Help parents apply quickly. If ineligible, signpost to other support rather than leaving them at a dead end."></textarea>
        </div>
        <div class="form-group">
          <label for="q3">What content principles should we apply?</label>
          <textarea id="q3" name="q3" rows="3" placeholder="Plain, warm and direct. No jargon. Use 'you' and 'your child' throughout."></textarea>
        </div>
        <div class="form-group">
          <label for="pdf">Upload a PDF (optional)</label>
          <p class="hint">Policy documents, existing service specs, research findings.</p>
          <label class="file-upload-label" for="pdf">
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M8 1v10M4 5l4-4 4 4" stroke="#0b0c0c" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M1 11v3h14v-3" stroke="#0b0c0c" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>
            Choose file
          </label>
          <input type="file" id="pdf" name="pdf" accept=".pdf">
          <div class="file-name" id="fileName">No file chosen</div>
        </div>
        <div class="form-group">
          <label for="url">Reference URL (optional)</label>
          <p class="hint">A live service or document to reference.</p>
          <input type="url" id="url" name="url" placeholder="https://www.gov.uk/example">
        </div>
        <button type="submit" class="generate-btn" id="generateBtn">
          <span id="btnText">Generate prototype</span>
          <svg class="btn-arrow" id="btnArrow" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60">
            <path d="M0 20h40l-8-8 4-4 16 16-16 16-4-4 8-8H0z"/>
          </svg>
        </button>
        <p class="form-footer">or <a href="/prototypes">view previously generated prototypes</a></p>
      </form>
      </div>

      <!-- Progress panel -->
      <div class="progress-panel" id="progressPanel">
        <div class="progress-bar-track">
          <div class="progress-bar-fill" id="progressBar"></div>
        </div>
        <ul class="progress-steps">
          <li id="step-pdf" style="display:none;"><span class="step-icon" id="icon-pdf">–</span> Reading document</li>
          <li id="step-claude"><span class="step-icon" id="icon-claude">–</span> Generating with Claude</li>
          <li id="step-github"><span class="step-icon" id="icon-github">–</span> Pushing to GitHub</li>
          <li id="step-render"><span class="step-icon" id="icon-render">–</span> Creating Render service</li>
          <li id="step-deploy"><span class="step-icon" id="icon-deploy">–</span> Waiting for prototype to go live</li>
        </ul>
      </div>

      <!-- Done panel -->
      <div class="done-panel" id="donePanel">
        <div class="done-header">
          <div class="done-tick-circle">
            <svg viewBox="0 0 24 24"><path d="M4 12l5 5L20 7"/></svg>
          </div>
          <div class="done-title">Your prototype is live</div>
        </div>
        <p class="done-sub">It is ready to use. Share the link with your team.</p>
        <a href="#" id="openProtoBtn" class="open-proto-btn" target="_blank" rel="noopener">Open prototype &#8594;</a>
        <div id="pdfTruncatedNotice" class="truncated-notice" style="display:none;">Your document was long so we summarised the most relevant parts. The prototype is based on that summary.</div>
      </div>

      <!-- Error panel -->
      <div class="error-panel" id="errorPanel">
        <div class="error-title">Something went wrong</div>
        <div class="error-msg" id="errorMsg"></div>
      </div>
    </div>

  </div>
</main>
<footer>Built on GOV.UK Prototype Kit v13 &middot; Powered by Claude</footer>

<script>
  document.getElementById('pdf').addEventListener('change', function() {
    document.getElementById('fileName').textContent = this.files[0] ? this.files[0].name : 'No file chosen';
  });

  // Step state helpers
  function setStep(stepId, iconId, state) {
    const li = document.getElementById(stepId);
    const icon = document.getElementById(iconId);
    li.className = state;
    if (state === 'active') icon.textContent = '●';
    else if (state === 'done') icon.textContent = '✓';
    else icon.textContent = '–';
  }

  // Timed fake progress that advances through steps on a schedule
  // Real done only fires when server responds
  let progressTimer = null;

  function startFakeProgress(hasPdf) {
    const bar = document.getElementById('progressBar');
    const pdfStep = document.getElementById('step-pdf');
    let steps;

    if (hasPdf) {
      pdfStep.style.display = '';
      steps = [
        { stepId: 'step-pdf',     iconId: 'icon-pdf',     delay: 0,     pct: 10 },
        { stepId: 'step-claude',  iconId: 'icon-claude',  delay: 12000, pct: 25 },
        { stepId: 'step-github',  iconId: 'icon-github',  delay: 24000, pct: 50 },
        { stepId: 'step-render',  iconId: 'icon-render',  delay: 36000, pct: 65 },
        { stepId: 'step-deploy',  iconId: 'icon-deploy',  delay: 50000, pct: 80 }
      ];
    } else {
      pdfStep.style.display = 'none';
      steps = [
        { stepId: 'step-claude',  iconId: 'icon-claude',  delay: 0,     pct: 15 },
        { stepId: 'step-github',  iconId: 'icon-github',  delay: 18000, pct: 45 },
        { stepId: 'step-render',  iconId: 'icon-render',  delay: 30000, pct: 65 },
        { stepId: 'step-deploy',  iconId: 'icon-deploy',  delay: 45000, pct: 80 }
      ];
    }

    let prevStepId = null, prevIconId = null;
    steps.forEach(function(s) {
      const t = setTimeout(function() {
        if (prevStepId) setStep(prevStepId, prevIconId, 'done');
        setStep(s.stepId, s.iconId, 'active');
        bar.style.width = s.pct + '%';
        prevStepId = s.stepId;
        prevIconId = s.iconId;
      }, s.delay);
      if (!progressTimer) progressTimer = [];
      progressTimer.push(t);
    });
  }

  function stopFakeProgress() {
    if (progressTimer) progressTimer.forEach(clearTimeout);
    progressTimer = null;
  }

  document.getElementById('generateForm').addEventListener('submit', async function(e) {
    e.preventDefault();

    const btn = document.getElementById('generateBtn');
    const btnText = document.getElementById('btnText');
    const btnArrow = document.getElementById('btnArrow');
    const progressPanel = document.getElementById('progressPanel');
    const donePanel = document.getElementById('donePanel');
    const errorPanel = document.getElementById('errorPanel');
    const bar = document.getElementById('progressBar');
    const hasPdf = document.getElementById('pdf').files.length > 0;

    // Reset UI
    donePanel.className = 'done-panel';
    errorPanel.className = 'error-panel';
    document.getElementById('pdfTruncatedNotice').style.display = 'none';
    progressPanel.className = 'progress-panel visible';
    bar.style.width = '5%';
    bar.className = 'progress-bar-fill';
    var allSteps = ['step-claude','step-github','step-render','step-deploy'];
    if (hasPdf) allSteps.unshift('step-pdf');
    allSteps.forEach(function(id) {
      document.getElementById(id).className = '';
      var iconId = 'icon-' + id.replace('step-', '');
      document.getElementById(iconId).textContent = '–';
    });

    btn.disabled = true;
    btnArrow.style.display = 'none';
    btnText.innerHTML = '<span class="spinner"></span> Generating&hellip;';

    startFakeProgress(hasPdf);

    try {
      const formData = new FormData(this);
      const response = await fetch('/generate-v2', { method: 'POST', body: formData });

      stopFakeProgress();

      if (!response.ok) {
        const err = await response.json().catch(function() { return { error: 'Unknown error' }; });
        throw new Error(err.error || 'Something went wrong');
      }

      const result = await response.json();

      // All steps done
      bar.style.width = '100%';
      bar.className = 'progress-bar-fill complete';
      var doneSteps = ['step-claude','step-github','step-render','step-deploy'];
      if (hasPdf) doneSteps.unshift('step-pdf');
      doneSteps.forEach(function(id) {
        setStep(id, 'icon-' + id.replace('step-', ''), 'done');
      });

      // Show done panel
      progressPanel.className = 'progress-panel';
      document.getElementById('openProtoBtn').href = result.url;
      donePanel.className = 'done-panel visible';

      // Show truncation notice if applicable
      if (result.pdfTruncated) {
        document.getElementById('pdfTruncatedNotice').style.display = 'block';
      }

    } catch (err) {
      stopFakeProgress();
      progressPanel.className = 'progress-panel';
      document.getElementById('errorMsg').textContent = err.message || 'Try again or simplify your brief.';
      errorPanel.className = 'error-panel visible';
    }

    btn.disabled = false;
    btnArrow.style.display = '';
    btnText.textContent = 'Generate prototype';
  });
</script>
</body>
</html>`);
});

// ─── v2 Generate endpoint ─────────────────────────────────────────────────────

app.post('/generate-v2', upload.single('pdf'), async (req, res) => {
  try {
    const { q1, q2, q3, url } = req.body;
    const brief = [q1, q2, q3].filter(Boolean).map((s, i) => {
      const labels = ['Users and needs', 'Service goals', 'Content principles'];
      return labels[i] + ': ' + s.trim();
    }).join('\n\n');
    const apiKey = process.env.ANTHROPIC_API_KEY;
    const githubToken = process.env.GITHUB_TOKEN;
    const renderApiKey = process.env.RENDER_API_KEY;
    const renderOwnerId = process.env.RENDER_OWNER_ID;
    const githubUsername = process.env.GITHUB_USERNAME;

    if (!apiKey) return res.status(500).json({ error: 'ANTHROPIC_API_KEY not set' });
    if (!githubToken) return res.status(500).json({ error: 'GITHUB_TOKEN not set' });
    if (!renderApiKey) return res.status(500).json({ error: 'RENDER_API_KEY not set' });
    if (!renderOwnerId) return res.status(500).json({ error: 'RENDER_OWNER_ID not set' });
    if (!githubUsername) return res.status(500).json({ error: 'GITHUB_USERNAME not set' });
    if (!q1 || q1.trim().length < 5) return res.status(400).json({ error: 'Tell us who the users are and what they need' });

    // Step 1: PDF summarisation
    let pdfSummary = null;
    let pdfTruncated = false;
    if (req.file) {
      try {
        const pdfData = await pdfParse(req.file.buffer);
        let pdfText = pdfData.text;
        if (pdfText.length > 15000) {
          if (pdfText.length > 80000) {
            pdfText = pdfText.slice(0, 80000);
            pdfTruncated = true;
          }
          try {
            const summaryResponse = await fetch('https://api.anthropic.com/v1/messages', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'x-api-key': apiKey,
                'anthropic-version': '2023-06-01'
              },
              body: JSON.stringify({
                model: 'claude-sonnet-4-20250514',
                max_tokens: 2000,
                system: 'You are a government policy analyst. You will receive a service brief and a policy document. Extract and summarise only the content relevant to the brief. Return a clean markdown summary covering: eligibility rules and criteria, evidence requirements, key process steps and timeframes, any user-facing terminology that must be used, and any exclusions or special cases. Be concise. Maximum 1500 words.',
                messages: [{ role: 'user', content: `Brief: ${brief.trim()}\n\nDocument:\n${pdfText}` }]
              })
            });
            if (summaryResponse.ok) {
              const summaryData = await summaryResponse.json();
              pdfSummary = summaryData.content[0].text.trim();
            }
          } catch (e) {
            console.error('PDF summarisation failed, continuing without summary:', e.message);
          }
        } else {
          pdfSummary = pdfText;
        }
      } catch (e) {
        console.error('PDF parsing failed:', e.message);
      }
    }

    // Step 2: Claude generation
    let userMessage = `Brief: ${brief.trim()}`;
    if (pdfSummary) {
      userMessage += `\n\nPolicy document summary — use this to inform eligibility rules, question wording, hints, confirmation content, and any guidance:\n${pdfSummary}`;
    }
    if (url && url.trim()) userMessage += `\n\nReference URL: ${url.trim()}`;
    userMessage += '\n\nReturn only the JSON object. No explanation. No markdown.';

    const claudeResponse = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 8000,
        system: gdsPromptV2,
        messages: [{ role: 'user', content: userMessage }]
      })
    });

    if (!claudeResponse.ok) {
      const err = await claudeResponse.json();
      throw new Error(err.error?.message || 'Claude API error');
    }

    const claudeData = await claudeResponse.json();
    const rawText = claudeData.content[0].text.trim();

    let spec;
    try {
      const clean = rawText.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/```\s*$/i, '').trim();
      spec = JSON.parse(clean);
    } catch (e) {
      throw new Error('Claude returned invalid JSON. Try simplifying your brief.');
    }

    if (!spec.serviceName || !spec.questions || spec.questions.length < 1) {
      throw new Error('Prototype spec incomplete. Try again.');
    }

    // Step 3: Build and push to GitHub
    const files = buildPrototypeFilesV2(spec);
    const timestamp = Date.now();
    const repoName = `prototype-${timestamp}`;

    await createGitHubRepo(repoName, githubToken);
    await pushAllFiles(githubUsername, repoName, files, githubToken);

    const repoUrl = `https://github.com/${githubUsername}/${repoName}`;

    // Step 3: Create Render service
    const serviceName = `prototype-${timestamp}`;
    const renderData = await createRenderService(repoUrl, serviceName, renderApiKey, renderOwnerId);

    const serviceId = renderData.service?.id;
    if (!serviceId) throw new Error('Render did not return a service ID');

    // Step 4: Poll until actually live
    const protoUrl = `https://${serviceName}.onrender.com`;
    await pollUntilLive(protoUrl);
    await new Promise(r => setTimeout(r, 20000));

    // Log it (fire and forget)
    appendToLog({
      serviceName: spec.serviceName,
      brief: brief.trim().slice(0, 120),
      url: protoUrl,
      repoUrl,
      createdAt: new Date().toISOString()
    }, githubUsername, githubToken).catch(e => console.error('Log write failed:', e));

    res.json({ url: protoUrl, repoUrl, pdfTruncated });

  } catch (err) {
    console.error(err);
    if (!res.headersSent) res.status(500).json({ error: err.message });
  }
});

// ─── Prototypes log page ──────────────────────────────────────────────────────

app.get('/prototypes', async (req, res) => {
  const githubToken = process.env.GITHUB_TOKEN;
  const githubUsername = process.env.GITHUB_USERNAME;
  const log = await getLog(githubUsername, githubToken);

  const pageSize = 10;
  const page = Math.max(1, parseInt(req.query.page, 10) || 1);
  const totalPages = Math.max(1, Math.ceil(log.length / pageSize));
  const currentPage = Math.min(page, totalPages);
  const start = (currentPage - 1) * pageSize;
  const pageLog = log.slice(start, start + pageSize);

  function timeAgo(iso) {
    const diff = Date.now() - new Date(iso).getTime();
    const mins = Math.floor(diff / 60000);
    const hours = Math.floor(diff / 3600000);
    const days = Math.floor(diff / 86400000);
    if (mins < 2) return 'just now';
    if (mins < 60) return mins + ' minutes ago';
    if (hours < 24) return hours + ' hour' + (hours > 1 ? 's' : '') + ' ago';
    return days + ' day' + (days > 1 ? 's' : '') + ' ago';
  }

  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>All prototypes – Prototype Engine</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "GDS Transport", arial, sans-serif; background: #f8f8f8; min-height: 100vh; display: flex; flex-direction: column; -webkit-font-smoothing: antialiased; }
    main { max-width: 960px; margin: 0 auto; padding: 50px 30px 60px; flex: 1; width: 100%; }
    .page-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 28px; flex-wrap: wrap; gap: 16px; }
    .page-header-left h1 { font-size: 36px; font-weight: 700; color: #0b0c0c; letter-spacing: -0.5px; }
    .page-header-left p { font-size: 15px; color: #6f777b; margin-top: 4px; }
    .proto-list { display: flex; flex-direction: column; gap: 8px; }
    .proto-card { background: white; padding: 22px 26px; display: flex; align-items: center; justify-content: space-between; gap: 24px; border-radius: 10px; box-shadow: 0 1px 3px rgba(0,0,0,0.05); border: 1px solid rgba(0,0,0,0.06); transition: box-shadow 0.2s ease, transform 0.2s ease; }
    .proto-card:hover { box-shadow: 0 4px 12px rgba(0,0,0,0.08); transform: translateY(-1px); }
    .proto-card-left { flex: 1; min-width: 0; }
    .proto-name { font-size: 18px; font-weight: 700; color: #0b0c0c; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
    .proto-meta { font-size: 14px; color: #6f777b; margin-top: 4px; }
    .proto-card-right { flex-shrink: 0; }
    .open-link { display: inline-flex; align-items: center; justify-content: center; gap: 6px; background: #1d70b8; color: white; text-decoration: none; padding: 10px 18px; font-size: 15px; font-weight: 700; font-family: inherit; border-radius: 6px; transition: background 0.15s, box-shadow 0.15s, transform 0.1s; box-shadow: 0 1px 3px rgba(29,112,184,0.15); }
    .open-link:hover { background: #003078; transform: translateY(-1px); box-shadow: 0 3px 6px rgba(29,112,184,0.2); }
    .empty-state { background: white; border: 1px solid rgba(0,0,0,0.06); border-radius: 12px; padding: 60px 30px; text-align: center; color: #6f777b; font-size: 17px; }
    .pagination { display: flex; align-items: center; justify-content: space-between; margin-top: 24px; font-size: 15px; }
    .pagination a { color: #1d70b8; font-weight: 700; text-decoration: none; padding: 8px 14px; border-radius: 6px; transition: background 0.15s; }
    .pagination a:hover { background: #e8f1f8; }
    .pagination .page-info { color: #6f777b; }
    .back-link { margin-top: 24px; font-size: 15px; }
    .back-link a { color: #6f777b; text-decoration: none; transition: color 0.15s; }
    .back-link a:hover { color: #1d70b8; }
    footer { background: #ffffff; padding: 24px 30px; color: #6f777b; font-size: 14px; text-align: center; border-top: 1px solid #e8e8e8; }
  </style>
</head>
<body>
<header style="background:#e0531a;padding:14px 0;">
  <div style="max-width:960px;margin:0 auto;padding:0 30px;">
    <a href="/" style="text-decoration:none;display:inline-flex;align-items:center;gap:10px;">
      <svg class="pe-logo" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="0" y="0" width="11" height="11" fill="white"/>
        <rect x="13" y="0" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="0" y="13" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="13" y="13" width="11" height="11" fill="white"/>
      </svg>
      <span style="color:white;font-size:15px;font-weight:700;font-family:arial,sans-serif;letter-spacing:-0.3px;">Prototype Engine</span>
    </a>
  </div>
</header>
<main>
  <div class="page-header">
    <div class="page-header-left">
      <h1>All prototypes</h1>
      <p>${log.length} generated</p>
    </div>
  </div>
  ${log.length === 0
    ? '<div class="empty-state">No prototypes generated yet.</div>'
    : '<div class="proto-list">' + pageLog.map(function(entry) {
        return '<div class="proto-card">' +
          '<div class="proto-card-left">' +
            '<div class="proto-name">' + entry.serviceName + '</div>' +
            '<div class="proto-meta">' + timeAgo(entry.createdAt) + '</div>' +
          '</div>' +
          '<div class="proto-card-right">' +
            '<a href="' + entry.url + '" target="_blank" rel="noopener" class="open-link">Open &#8594;</a>' +
          '</div>' +
        '</div>';
      }).join('') + '</div>'
  }
  ${totalPages > 1 ? '<nav class="pagination">' +
    (currentPage > 1 ? '<a href="/prototypes?page=' + (currentPage - 1) + '">&larr; Newer</a>' : '<span></span>') +
    '<span class="page-info">Page ' + currentPage + ' of ' + totalPages + '</span>' +
    (currentPage < totalPages ? '<a href="/prototypes?page=' + (currentPage + 1) + '">Older &rarr;</a>' : '<span></span>') +
    '</nav>' : ''}
  <p class="back-link"><a href="/">&larr; Back</a></p>
</main>
<footer>Built on GOV.UK Prototype Kit v13 &middot; Powered by Claude</footer>
</body>
</html>`);
});

// ─── Design history ──────────────────────────────────────────────────────────

function renderDesignHistoryEntry(entry) {
  var whatChangedHtml = '';
  if (entry.whatChanged && entry.whatChanged.length > 0) {
    whatChangedHtml = '<ul style="font-size:18px;line-height:1.7;padding-left:20px;margin-top:10px;color:#0b0c0c;">' +
      entry.whatChanged.map(function(item) { return '<li style="margin-bottom:4px;">' + item + '</li>'; }).join('') +
      '</ul>';
  } else {
    whatChangedHtml = '<p style="font-size:18px;line-height:1.6;color:#6f777b;">None yet.</p>';
  }
  return '<div style="margin-bottom:40px;padding:32px;background:white;border-radius:12px;box-shadow:0 1px 3px rgba(0,0,0,0.05);border:1px solid rgba(0,0,0,0.06);">' +
    '<h2 style="font-size:30px;font-weight:700;color:#0b0c0c;margin-bottom:6px;letter-spacing:-0.3px;">' + entry.title + '</h2>' +
    '<p style="font-size:14px;color:#6f777b;margin-bottom:28px;">Last updated: ' + entry.date + '</p>' +
    '<h3 style="font-size:22px;font-weight:700;color:#0b0c0c;margin-bottom:10px;">Problem</h3>' +
    '<p style="font-size:18px;line-height:1.6;margin-bottom:28px;color:#0b0c0c;">' + entry.problem + '</p>' +
    '<h3 style="font-size:22px;font-weight:700;color:#0b0c0c;margin-bottom:10px;">Our approach</h3>' +
    '<p style="font-size:18px;line-height:1.6;margin-bottom:28px;color:#0b0c0c;">' + entry.approach + '</p>' +
    '<h3 style="font-size:22px;font-weight:700;color:#0b0c0c;margin-bottom:10px;">What changed</h3>' +
    '<div style="margin-bottom:28px;">' + whatChangedHtml + '</div>' +
    '<h3 style="font-size:22px;font-weight:700;color:#0b0c0c;margin-bottom:10px;">Next steps</h3>' +
    '<p style="font-size:18px;line-height:1.6;color:#0b0c0c;">' + entry.nextSteps + '</p>' +
  '</div>';
}

app.get('/design-history', (req, res) => {
  var v1 = JSON.parse(fs.readFileSync(path.join(__dirname, 'app', 'design-history', 'v1.json'), 'utf8'));
  var v2 = JSON.parse(fs.readFileSync(path.join(__dirname, 'app', 'design-history', 'v2.json'), 'utf8'));
  var v3 = JSON.parse(fs.readFileSync(path.join(__dirname, 'app', 'design-history', 'v3.json'), 'utf8'));
  var versions = [v1, v2, v3];

  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Design history – Prototype Engine</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "GDS Transport", arial, sans-serif; background: #f8f8f8; min-height: 100vh; display: flex; flex-direction: column; -webkit-font-smoothing: antialiased; }
    main { max-width: 960px; margin: 0 auto; padding: 50px 30px 60px; flex: 1; width: 100%; }
    h1 { font-size: 42px; font-weight: 700; color: #0b0c0c; line-height: 1.1; margin-bottom: 8px; letter-spacing: -0.5px; }
    .lede { font-size: 19px; color: #505a5f; margin-bottom: 36px; line-height: 1.5; }
    .version-list { list-style: none; padding: 0; display: flex; flex-direction: column; gap: 10px; }
    .version-card { background: white; padding: 24px 28px; display: flex; align-items: center; justify-content: space-between; gap: 20px; border-radius: 10px; box-shadow: 0 1px 3px rgba(0,0,0,0.05); border: 1px solid rgba(0,0,0,0.06); transition: box-shadow 0.2s ease, transform 0.2s ease; }
    .version-card:hover { box-shadow: 0 4px 12px rgba(0,0,0,0.08); transform: translateY(-1px); }
    .version-info { flex: 1; }
    .version-name { font-size: 20px; font-weight: 700; color: #1d70b8; text-decoration: none; transition: color 0.15s; }
    .version-name:hover { color: #003078; }
    .version-date { font-size: 14px; color: #6f777b; margin-top: 4px; }
    footer { background: #ffffff; padding: 24px 30px; color: #6f777b; font-size: 14px; text-align: center; border-top: 1px solid #e8e8e8; }
    @media (max-width: 768px) { h1 { font-size: 32px; } }
  </style>
</head>
<body>
<header style="background:#e0531a;padding:14px 0;">
  <div style="max-width:960px;margin:0 auto;padding:0 30px;">
    <a href="/" style="text-decoration:none;display:inline-flex;align-items:center;gap:10px;">
      <svg class="pe-logo" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="0" y="0" width="11" height="11" fill="white"/>
        <rect x="13" y="0" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="0" y="13" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="13" y="13" width="11" height="11" fill="white"/>
      </svg>
      <span style="color:white;font-size:15px;font-weight:700;font-family:arial,sans-serif;letter-spacing:-0.3px;">Prototype Engine</span>
    </a>
  </div>
</header>
<main>
  <h1>Design history</h1>
  <p class="lede">A record of what we built, why we built it, and what changed in each version.</p>
  <ul class="version-list">
` + versions.map(function(v) {
    var latestDate = v.entries[0] ? v.entries[0].date : '';
    return '    <li class="version-card"><div class="version-info"><a href="/design-history/' + v.version + '" class="version-name">' + v.version + ': ' + v.title + '</a><p class="version-date">' + latestDate + '</p></div></li>';
  }).join('\n') + `
  </ul>
</main>
<footer>Built on GOV.UK Prototype Kit v13 &middot; Powered by Claude</footer>
</body>
</html>`);
});

app.get('/design-history/:version', (req, res) => {
  var version = req.params.version;
  var filePath = path.join(__dirname, 'app', 'design-history', version + '.json');
  if (!fs.existsSync(filePath)) {
    return res.status(404).send('Not found');
  }
  var data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  var entriesHtml = data.entries.map(renderDesignHistoryEntry).join('');

  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${data.version}: ${data.title} – Design history – Prototype Engine</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "GDS Transport", arial, sans-serif; background: #f8f8f8; min-height: 100vh; display: flex; flex-direction: column; -webkit-font-smoothing: antialiased; }
    main { max-width: 960px; margin: 0 auto; padding: 50px 30px 60px; flex: 1; width: 100%; }
    .back-link { font-size: 15px; margin-bottom: 24px; }
    .back-link a { color: #6f777b; text-decoration: none; transition: color 0.15s; }
    .back-link a:hover { color: #1d70b8; }
    footer { background: #ffffff; padding: 24px 30px; color: #6f777b; font-size: 14px; text-align: center; border-top: 1px solid #e8e8e8; }
    @media (max-width: 768px) { h1 { font-size: 32px; } }
  </style>
</head>
<body>
<header style="background:#e0531a;padding:14px 0;">
  <div style="max-width:960px;margin:0 auto;padding:0 30px;">
    <a href="/" style="text-decoration:none;display:inline-flex;align-items:center;gap:10px;">
      <svg class="pe-logo" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="0" y="0" width="11" height="11" fill="white"/>
        <rect x="13" y="0" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="0" y="13" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="13" y="13" width="11" height="11" fill="white"/>
      </svg>
      <span style="color:white;font-size:15px;font-weight:700;font-family:arial,sans-serif;letter-spacing:-0.3px;">Prototype Engine</span>
    </a>
  </div>
</header>
<main>
  <p class="back-link"><a href="/design-history">&larr; Back to design history</a></p>
  <h1 style="font-size:42px;font-weight:700;color:#0b0c0c;line-height:1.15;margin-bottom:36px;letter-spacing:-0.5px;">${data.version}: ${data.title}</h1>
  ${entriesHtml}
</main>
<footer>Built on GOV.UK Prototype Kit v13 &middot; Powered by Claude</footer>
</body>
</html>`);
});

app.get('/roadmap', (req, res) => {
  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>How the tool works – Prototype Engine</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "GDS Transport", arial, sans-serif; background: #f8f8f8; min-height: 100vh; display: flex; flex-direction: column; -webkit-font-smoothing: antialiased; }
    main { max-width: 960px; margin: 0 auto; padding: 50px 30px 60px; flex: 1; width: 100%; }
    .govuk-width-container { max-width: 640px; }
    .govuk-heading-l { font-size: 42px; font-weight: 700; color: #0b0c0c; line-height: 1.15; margin-bottom: 30px; letter-spacing: -0.5px; }
    .govuk-heading-m { font-size: 24px; font-weight: 700; color: #0b0c0c; margin-top: 40px; margin-bottom: 15px; }
    .govuk-body { font-size: 18px; color: #0b0c0c; line-height: 1.6; margin-bottom: 20px; }
    .govuk-list { font-size: 18px; color: #0b0c0c; line-height: 1.7; margin-bottom: 20px; padding-left: 0; list-style: none; }
    .govuk-list--bullet { padding-left: 20px; list-style-type: disc; }
    .govuk-list--bullet li { margin-bottom: 5px; }
    footer { background: #ffffff; padding: 24px 30px; color: #6f777b; font-size: 14px; text-align: center; border-top: 1px solid #e8e8e8; }
    @media (max-width: 768px) { .govuk-heading-l { font-size: 32px; } .govuk-heading-m { font-size: 20px; } }
  </style>
</head>
<body>
<header style="background:#e0531a;padding:14px 0;">
  <div style="max-width:960px;margin:0 auto;padding:0 30px;">
    <a href="/" style="text-decoration:none;display:inline-flex;align-items:center;gap:10px;">
      <svg class="pe-logo" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="0" y="0" width="11" height="11" fill="white"/>
        <rect x="13" y="0" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="0" y="13" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="13" y="13" width="11" height="11" fill="white"/>
      </svg>
      <span style="color:white;font-size:15px;font-weight:700;font-family:arial,sans-serif;letter-spacing:-0.3px;">Prototype Engine</span>
    </a>
  </div>
</header>
<main>
  <div class="govuk-width-container">
    <h1 class="govuk-heading-l">How the tool works</h1>

    <h2 class="govuk-heading-m">What it does</h2>
    <p class="govuk-body">This tool is a research and development project exploring how AI can help content designers prototype GOV.UK services faster. It generates a working prototype from a plain English brief in around 5 minutes — no code required.</p>

    <h2 class="govuk-heading-m">Who it is for</h2>
    <p class="govuk-body">It is designed for content designers. It can also be used by product managers, policy professionals, and user researchers.</p>

    <h2 class="govuk-heading-m">Why it works this way</h2>
    <p class="govuk-body">The tool wraps Claude in a controlled environment. This makes output consistent, predictable, and shareable across the team. Each release is tested for stability before new capabilities are added. If something goes wrong, we can roll back without affecting what already works.</p>

    <h2 class="govuk-heading-m">What it does well</h2>
    <p class="govuk-body">Every prototype includes:</p>
    <ul class="govuk-list govuk-list--bullet">
      <li>A start page, question pages, check your answers, and a confirmation screen</li>
      <li>Validation on every question</li>
      <li>Automatic deployment to a shareable URL</li>
    </ul>
    <p class="govuk-body">Version 2 adds branching journeys, where different answers lead to different pages.</p>

    <h2 class="govuk-heading-m">Current limitations</h2>
    <p class="govuk-body">The tool is at an early stage. The biggest limitation right now is content and design quality.</p>
    <p class="govuk-body">Specifically:</p>
    <ul class="govuk-list govuk-list--bullet">
      <li>Generated content is functional but lacks the design thinking a content designer would apply manually</li>
      <li>Question wording, hint text, and confirmation pages often need significant revision</li>
      <li>Journeys cover the main flow but not edge cases, exception routes, or nuanced policy decisions</li>
      <li>The full range of GDS patterns is not yet supported</li>
    </ul>
    <p class="govuk-body">Improving content and design quality is the primary focus of v3.</p>

    <h2 class="govuk-heading-m">Known unknowns</h2>
    <p class="govuk-body">As an R&D project, there are things we are still working out:</p>
    <ul class="govuk-list govuk-list--bullet">
      <li>How much complexity the tool can support before the workflow breaks down</li>
      <li>How it performs with multiple concurrent users</li>
      <li>How much work a future GOV.UK Prototype Kit update would require</li>
    </ul>

    <h2 class="govuk-heading-m">Next steps</h2>
    <p class="govuk-body">Each version introduces one new capability, tested for stability before the next begins.</p>

    <div style="max-width:560px;margin:24px 0;font-family:'GDS Transport',arial,sans-serif;">
      <div style="padding:14px 20px;margin-bottom:4px;background:#0b5c3e;width:100%;display:flex;align-items:center;justify-content:space-between;">
        <span style="font-size:15px;font-weight:700;color:white;">v1 — Foundation</span>
        <span style="font-size:11px;font-weight:700;padding:2px 8px;text-transform:uppercase;letter-spacing:0.05em;background:#00703c;color:white;">Stable</span>
      </div>
      <div style="padding:14px 20px;margin-bottom:4px;background:#1d70b8;width:80%;display:flex;align-items:center;justify-content:space-between;">
        <span style="font-size:15px;font-weight:700;color:white;">v2 — Branching</span>
        <span style="font-size:11px;font-weight:700;padding:2px 8px;text-transform:uppercase;letter-spacing:0.05em;background:#003078;color:white;">In testing</span>
      </div>
      <div style="padding:14px 20px;margin-bottom:4px;background:#505a5f;width:60%;display:flex;align-items:center;justify-content:space-between;">
        <span style="font-size:15px;font-weight:700;color:white;">v3 — Content and patterns</span>
        <span style="font-size:11px;font-weight:700;padding:2px 8px;text-transform:uppercase;letter-spacing:0.05em;background:#383f43;color:white;">Planned</span>
      </div>
      <div style="padding:14px 20px;margin-bottom:4px;background:#b1b4b6;width:55%;display:flex;align-items:center;justify-content:space-between;">
        <span style="font-size:15px;font-weight:700;color:#0b0c0c;">v4 — Edit mode</span>
        <span style="font-size:11px;font-weight:700;padding:2px 8px;text-transform:uppercase;letter-spacing:0.05em;background:#6f777b;color:white;">Planned</span>
      </div>
      <p style="font-size:13px;color:#505a5f;margin-top:16px;">Each layer is confirmed stable before the next begins.</p>
    </div>
  </div>
</main>
<footer>Built on GOV.UK Prototype Kit v13 &middot; Powered by Claude</footer>
</body>
</html>`);
});

const port = process.env.PORT || 3000;
app.listen(port, () => console.log(`Prototype Engine running on port ${port}`));
