const express = require('express');
const multer = require('multer');
const fetch = require('node-fetch');
const pdfParse = require('pdf-parse');
const gdsPrompt = require('./gds-prompt');
const { buildPrototypeFiles } = require('./generator');

const app = express();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 } });

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// ─── GitHub helpers ───────────────────────────────────────────────────────────

async function createGitHubRepo(repoName, token) {
  const res = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers: {
      'Authorization': `token ${token}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      name: repoName,
      private: false,
      auto_init: false,
      description: 'GOV.UK prototype generated by Prototype Engine'
    })
  });
  if (!res.ok) {
    const err = await res.json();
    throw new Error(`GitHub repo creation failed: ${err.message}`);
  }
  return await res.json();
}

async function pushFileToGitHub(owner, repo, filePath, content, token) {
  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`, {
    method: 'PUT',
    headers: {
      'Authorization': `token ${token}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      message: `Add ${filePath}`,
      content: Buffer.from(content).toString('base64')
    })
  });
  if (!res.ok) {
    const err = await res.json();
    throw new Error(`Failed to push ${filePath}: ${err.message}`);
  }
  return await res.json();
}

async function pushAllFiles(owner, repoName, files, token) {
  for (const [filePath, content] of Object.entries(files)) {
    await pushFileToGitHub(owner, repoName, filePath, content, token);
    await new Promise(r => setTimeout(r, 200));
  }
}

// ─── Render helpers ───────────────────────────────────────────────────────────

async function createRenderService(repoUrl, serviceName, renderApiKey, ownerId) {
  const res = await fetch('https://api.render.com/v1/services', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${renderApiKey}`,
      'Content-Type': 'application/json',
      'Accept': 'application/json'
    },
    body: JSON.stringify({
      type: 'web_service',
      name: serviceName,
      ownerId: ownerId,
      repo: repoUrl,
      branch: 'main',
      autoDeploy: 'yes',
      serviceDetails: {
        env: 'node',
        buildCommand: 'npm install',
        startCommand: 'npm start',
        plan: 'free',
        region: 'oregon',
        envSpecificDetails: {
          buildCommand: 'npm install',
          startCommand: 'npm start'
        }
      }
    })
  });
  if (!res.ok) {
    const err = await res.json();
    throw new Error(`Render service creation failed: ${JSON.stringify(err)}`);
  }
  return await res.json();
}

async function pollUntilLive(protoUrl, maxWaitMs = 300000) {
  const start = Date.now();
  while (Date.now() - start < maxWaitMs) {
    await new Promise(r => setTimeout(r, 15000));
    try {
      const res = await fetch(protoUrl, { timeout: 10000 });
      if (res.ok || res.status === 302 || res.status === 301) return true;
    } catch (e) {
      // still deploying
    }
  }
  throw new Error('Prototype took too long to deploy. Try opening the link in a minute.');
}

// ─── Prototype log helpers ────────────────────────────────────────────────────

const LOG_REPO = 'proto-engine-0x';
const LOG_FILE = 'prototypes-log.json';

async function appendToLog(entry, owner, token) {
  let existingLog = [];
  let sha = null;
  try {
    const res = await fetch(`https://api.github.com/repos/${owner}/${LOG_REPO}/contents/${LOG_FILE}`, {
      headers: { 'Authorization': `token ${token}`, 'Accept': 'application/vnd.github.v3+json' }
    });
    if (res.ok) {
      const data = await res.json();
      sha = data.sha;
      existingLog = JSON.parse(Buffer.from(data.content, 'base64').toString('utf8'));
    }
  } catch (e) {}

  existingLog.unshift(entry);
  if (existingLog.length > 200) existingLog = existingLog.slice(0, 200);

  const body = {
    message: `Log prototype: ${entry.serviceName}`,
    content: Buffer.from(JSON.stringify(existingLog, null, 2)).toString('base64')
  };
  if (sha) body.sha = sha;

  await fetch(`https://api.github.com/repos/${owner}/${LOG_REPO}/contents/${LOG_FILE}`, {
    method: 'PUT',
    headers: {
      'Authorization': `token ${token}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(body)
  });
}

async function getLog(owner, token) {
  try {
    const res = await fetch(`https://api.github.com/repos/${owner}/${LOG_REPO}/contents/${LOG_FILE}`, {
      headers: { 'Authorization': `token ${token}`, 'Accept': 'application/vnd.github.v3+json' }
    });
    if (!res.ok) return [];
    const data = await res.json();
    return JSON.parse(Buffer.from(data.content, 'base64').toString('utf8'));
  } catch (e) {
    return [];
  }
}

// ─── Frontend ─────────────────────────────────────────────────────────────────

app.get('/', (req, res) => {
  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>GOV.UK Prototype Engine</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "GDS Transport", arial, sans-serif; background: #f3f2f1; min-height: 100vh; display: flex; flex-direction: column; }
    .govuk-header { background: #0b0c0c; padding: 12px 0; border-bottom: 10px solid #1d70b8; }
    .govuk-header__inner { max-width: 960px; margin: 0 auto; padding: 0 30px; display: flex; align-items: center; gap: 20px; }
    .govuk-header__crown { display: flex; align-items: center; gap: 10px; color: white; text-decoration: none; }
    .crown-svg { width: 36px; height: 32px; fill: white; }
    .govuk-header__logotype-text { font-size: 30px; font-weight: 700; color: white; letter-spacing: -1px; }
    .govuk-header__service-name { color: white; font-size: 19px; font-weight: 400; border-left: 1px solid #626a6e; padding-left: 20px; margin-left: 10px; }
    main { max-width: 960px; margin: 0 auto; padding: 40px 30px; flex: 1; width: 100%; }
    .two-col { display: grid; grid-template-columns: 2fr 1fr; gap: 60px; align-items: start; }
    h1 { font-size: 48px; font-weight: 700; color: #0b0c0c; line-height: 1.1; margin-bottom: 20px; }
    .lede { font-size: 20px; color: #0b0c0c; margin-bottom: 40px; line-height: 1.5; }
    label { display: block; font-size: 19px; font-weight: 700; color: #0b0c0c; margin-bottom: 8px; }
    .hint { font-size: 16px; color: #505a5f; margin-bottom: 10px; }
    textarea, input[type="text"], input[type="url"] { width: 100%; padding: 10px; font-size: 19px; font-family: inherit; border: 2px solid #0b0c0c; border-radius: 0; background: white; color: #0b0c0c; margin-bottom: 24px; }
    textarea:focus, input:focus { outline: 3px solid #ffdd00; outline-offset: 0; box-shadow: inset 0 0 0 2px #0b0c0c; }
    textarea { resize: vertical; }
    .file-upload-label { display: inline-block; padding: 8px 14px; background: #f3f2f1; border: 2px solid #0b0c0c; cursor: pointer; font-size: 16px; margin-bottom: 8px; }
    .file-name { font-size: 16px; color: #505a5f; margin-bottom: 24px; }
    input[type="file"] { display: none; }
    .generate-btn { background: #00703c; color: white; border: none; padding: 13px 22px; font-size: 19px; font-weight: 700; font-family: inherit; cursor: pointer; display: flex; align-items: center; gap: 10px; }
    .generate-btn:hover { background: #005a30; }
    .generate-btn:focus { outline: 3px solid #ffdd00; outline-offset: 0; }
    .generate-btn:disabled { background: #00703c; opacity: 0.75; cursor: wait; }
    .btn-arrow { width: 20px; height: 20px; fill: white; }

    /* Progress bar */
    .progress-panel { display: none; margin-top: 24px; background: white; border: 1px solid #d8dde0; border-radius: 6px; padding: 24px; }
    .progress-panel.visible { display: block; animation: fadeIn 0.2s ease; }
    .progress-bar-track { background: #f3f2f1; height: 4px; margin-bottom: 24px; border-radius: 2px; overflow: hidden; }
    .progress-bar-fill { height: 4px; background: #1d70b8; width: 0%; transition: width 0.6s ease; border-radius: 2px; }
    .progress-bar-fill.complete { background: #00703c; }
    .progress-steps { list-style: none; padding: 0; }
    .progress-steps li { font-size: 14px; color: #b1b4b6; padding: 9px 0; display: flex; align-items: center; gap: 12px; border-bottom: 1px solid #f3f2f1; transition: color 0.2s; }
    .progress-steps li:last-child { border-bottom: none; }
    .progress-steps li.active { color: #0b0c0c; font-weight: 600; }
    .progress-steps li.done { color: #00703c; }
    .step-icon { width: 16px; text-align: center; font-size: 12px; flex-shrink: 0; }

    /* Done panel */
    .done-panel { display: none; margin-top: 30px; background: white; border-left: 5px solid #00703c; padding: 24px; }
    .done-panel.visible { display: block; animation: fadeIn 0.4s ease; }
    @keyframes fadeIn { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: translateY(0); } }
    .done-header { display: flex; align-items: center; gap: 14px; margin-bottom: 16px; }
    .done-tick-circle { width: 40px; height: 40px; border-radius: 50%; background: #00703c; display: flex; align-items: center; justify-content: center; flex-shrink: 0; animation: popIn 0.4s cubic-bezier(0.34,1.56,0.64,1) both; }
    @keyframes popIn { from { transform: scale(0); } to { transform: scale(1); } }
    .done-tick-circle svg { width: 22px; height: 22px; fill: none; stroke: white; stroke-width: 3; stroke-linecap: round; stroke-linejoin: round; }
    .done-tick-circle svg path { stroke-dasharray: 40; stroke-dashoffset: 40; animation: drawTick 0.35s ease 0.3s forwards; }
    @keyframes drawTick { to { stroke-dashoffset: 0; } }
    .done-title { font-size: 24px; font-weight: 700; color: #0b0c0c; }
    .done-sub { font-size: 16px; color: #505a5f; margin-bottom: 20px; }
    .open-proto-btn { display: inline-block; background: #1d70b8; color: white; padding: 12px 20px; font-size: 19px; font-weight: 700; font-family: inherit; text-decoration: none; }
    .open-proto-btn:hover { background: #003078; }

    /* Error panel */
    .error-panel { display: none; margin-top: 30px; background: white; border-left: 5px solid #d4351c; padding: 24px; }
    .error-panel.visible { display: block; }
    .error-title { font-size: 19px; font-weight: 700; color: #0b0c0c; margin-bottom: 8px; }
    .error-msg { font-size: 16px; color: #505a5f; }

    /* Spinner */
    .spinner { display: inline-block; width: 16px; height: 16px; border: 2px solid rgba(255,255,255,0.4); border-top-color: white; border-radius: 50%; animation: spin 0.7s linear infinite; }
    @keyframes spin { to { transform: rotate(360deg); } }

    .steps { background: white; padding: 28px; border: 1px solid #d8dde0; border-radius: 6px; }
    .steps h2 { font-size: 11px; font-weight: 700; color: #6f777b; letter-spacing: 0.1em; text-transform: uppercase; margin-bottom: 20px; }
    .steps ol { list-style: none; padding: 0; }
    .steps li { font-size: 15px; color: #0b0c0c; line-height: 1.5; display: flex; gap: 14px; align-items: flex-start; padding: 10px 0; border-bottom: 1px solid #f3f2f1; }
    .steps li:last-child { border-bottom: none; }
    .step-num { font-size: 11px; font-weight: 700; color: #1d70b8; background: #e8f0fb; border-radius: 50%; min-width: 20px; height: 20px; display: inline-flex; align-items: center; justify-content: center; flex-shrink: 0; margin-top: 2px; }
    .all-protos-link { display: inline-flex; align-items: center; gap: 6px; margin-top: 20px; font-size: 14px; font-weight: 600; color: #1d70b8; text-decoration: none; border-top: 1px solid #f3f2f1; padding-top: 20px; width: 100%; }
    .all-protos-link:hover { color: #003078; }

    footer { background: #0b0c0c; padding: 20px 30px; color: #bfc1c3; font-size: 14px; text-align: center; }
    @media (max-width: 768px) { .two-col { grid-template-columns: 1fr; } h1 { font-size: 32px; } }
  </style>
</head>
<body>
<header class="govuk-header">
  <div class="govuk-header__inner">
    <a href="/" class="govuk-header__crown">
      <svg class="crown-svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 132 97" focusable="false">
        <path d="M25 30.2c3.5 1.5 7.7-.2 9.1-3.7 1.5-3.6-.2-7.8-3.9-9.2-3.6-1.4-7.6.3-9.1 3.9-1.4 3.5.3 7.5 3.9 9zM9 39.5c3.6 1.5 7.8-.2 9.2-3.7 1.5-3.6-.3-7.8-3.9-9.1-3.6-1.5-7.6.2-9.1 3.8-1.4 3.5.3 7.5 3.8 9zM4.4 57.2c3.5 1.5 7.7-.2 9.1-3.8 1.5-3.6-.2-7.7-3.9-9.1-3.5-1.5-7.6.3-9.1 3.8-1.4 3.5.3 7.6 3.9 9.1zm38.3-21.4c3.5 1.5 7.7-.2 9.1-3.8 1.5-3.6-.2-7.7-3.9-9.1-3.6-1.5-7.6.3-9.1 3.8-1.3 3.6.4 7.7 3.9 9.1zm64.4-5.6c-3.6 1.5-7.8-.2-9.1-3.7-1.5-3.6.2-7.8 3.8-9.2 3.6-1.4 7.7.3 9.2 3.9 1.3 3.5-.4 7.5-3.9 9zm15.9 9.3c-3.6 1.5-7.7-.2-9.1-3.7-1.5-3.6.2-7.8 3.7-9.1 3.6-1.5 7.7.2 9.2 3.8 1.5 3.5-.3 7.5-3.8 9zm4.7 17.7c-3.6 1.5-7.8-.2-9.2-3.8-1.5-3.6.2-7.7 3.9-9.1 3.6-1.5 7.7.3 9.2 3.8 1.3 3.5-.4 7.6-3.9 9.1zM89.3 35.8c-3.6 1.5-7.8-.2-9.2-3.8-1.4-3.6.2-7.7 3.9-9.1 3.6-1.5 7.7.3 9.2 3.8 1.4 3.6-.3 7.7-3.9 9.1zM69.7 17.7l8.9 4.7V9.3l-8.9 2.8c-.2-.3-.5-.6-.9-.9L72.4 0H59.6l3.5 11.2c-.3.3-.6.5-.9.9l-8.8-2.8v13.1l8.8-4.7c.3.3.6.7.9.9l-5 15.4v.1h14.2v-.1l-5-15.4c.4-.2.7-.6 1-.9zM66 92.8c16.9 0 32.8 1.1 47.1 3.2 4-16.9 8.9-26.7 14-33.5l-9.6-3.4c1 4.9 1.1 7.2 0 10.2-1.5-1.4-3-4.3-4.2-8.7L108.6 76c2.8-2 5-3.2 7.5-3.3-4.4 9.4-10 11.9-13.6 11.2-4.3-.8-6.3-4.6-5.6-7.9 1-4.7 5.7-5.9 8-.5 4.3-8.7-3-11.4-7.6-8.8 7.1-7.2 7.9-13.5 2.1-21.1-8 6.1-8.1 12.3-4.5 20.8-4.7-5.4-12.1-2.5-9.5 6.2 3.4-5.2 7.9-2 7.2 3.1-.6 4.3-6.4 7.8-13.5 7.2-10.3-.9-10.9-8-11.2-13.8 2.5-.5 7.1 1.8 11 7.3L80.2 60c-4.1 4.4-8 5.3-12.3 5.4 1.4-4.4 8-11.6 8-11.6H55.5s6.4 7.2 7.9 11.6c-4.2-.1-8-1-12.3-5.4l1.4 16.4c3.9-5.5 8.5-7.7 10.9-7.3-.3 5.8-.9 12.8-11.1 13.8-7.2.6-12.9-2.9-13.5-7.2-.7-5 3.8-8.3 7.1-3.1 2.7-8.7-4.6-11.6-9.4-6.2 3.7-8.5 3.6-14.7-4.6-20.8-5.8 7.6-5 13.9 2.2 21.1-4.7-2.6-11.9.1-7.7 8.8 2.3-5.5 7.1-4.2 8.1.5.7 3.3-1.3 7.1-5.7 7.9-3.5.7-9-1.8-13.5-11.2 2.5.1 4.7 1.3 7.5 3.3l-4.7-15.4c-1.2 4.4-2.7 7.2-4.3 8.7-1.1-3-.9-5.3 0-10.2l-9.5 3.4c5 6.9 9.9 16.7 14 33.5 14.8-2.1 30.8-3.2 47.7-3.2z"/>
      </svg>
      <span class="govuk-header__logotype-text">GOV.UK</span>
    </a>
    <span class="govuk-header__service-name">Prototype Engine</span>
  </div>
</header>
<main>
  <div class="two-col">
    <div>
      <h1>Build a GOV.UK prototype</h1>
      <p class="lede">Describe the service you need to prototype. One sentence is enough.</p>
      <form id="generateForm" enctype="multipart/form-data">
        <div>
          <label for="brief">Describe your service</label>
          <p class="hint">What does the user need to do, and why?</p>
          <textarea id="brief" name="brief" rows="5" placeholder="Example: A service for parents to apply for free school meals for their child."></textarea>
        </div>
        <div>
          <label for="pdf">Upload a PDF (optional)</label>
          <p class="hint">Policy documents, existing service specs, research findings.</p>
          <label class="file-upload-label" for="pdf">Choose file</label>
          <input type="file" id="pdf" name="pdf" accept=".pdf">
          <div class="file-name" id="fileName">No file chosen</div>
        </div>
        <div>
          <label for="url">Reference URL (optional)</label>
          <p class="hint">A live service or document to reference.</p>
          <input type="url" id="url" name="url" placeholder="https://www.gov.uk/example">
        </div>
        <button type="submit" class="generate-btn" id="generateBtn">
          <span id="btnText">Generate prototype</span>
          <svg class="btn-arrow" id="btnArrow" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60">
            <path d="M0 20h40l-8-8 4-4 16 16-16 16-4-4 8-8H0z"/>
          </svg>
        </button>
      </form>

      <!-- Progress panel -->
      <div class="progress-panel" id="progressPanel">
        <div class="progress-bar-track">
          <div class="progress-bar-fill" id="progressBar"></div>
        </div>
        <ul class="progress-steps">
          <li id="step-claude"><span class="step-icon" id="icon-claude">–</span> Generating with Claude</li>
          <li id="step-github"><span class="step-icon" id="icon-github">–</span> Pushing to GitHub</li>
          <li id="step-render"><span class="step-icon" id="icon-render">–</span> Creating Render service</li>
          <li id="step-deploy"><span class="step-icon" id="icon-deploy">–</span> Waiting for prototype to go live</li>
        </ul>
      </div>

      <!-- Done panel -->
      <div class="done-panel" id="donePanel">
        <div class="done-header">
          <div class="done-tick-circle">
            <svg viewBox="0 0 24 24"><path d="M4 12l5 5L20 7"/></svg>
          </div>
          <div class="done-title">Your prototype is live</div>
        </div>
        <p class="done-sub">It is ready to use. Share the link with your team.</p>
        <a href="#" id="openProtoBtn" class="open-proto-btn" target="_blank" rel="noopener">Open prototype</a>
      </div>

      <!-- Error panel -->
      <div class="error-panel" id="errorPanel">
        <div class="error-title">Something went wrong</div>
        <div class="error-msg" id="errorMsg"></div>
      </div>
    </div>

    <div class="steps">
      <h2>How it works</h2>
      <ol>
        <li><span class="step-num">1</span>Describe your service — one line is enough.</li>
        <li><span class="step-num">2</span>Click Generate.</li>
        <li><span class="step-num">3</span>Wait ~3 minutes while Claude builds and deploys it.</li>
        <li><span class="step-num">4</span>Open your live prototype and share the link.</li>
      </ol>
      <a href="/prototypes" class="all-protos-link">View all prototypes &rarr;</a>
    </div>
  </div>
</main>
<footer>Built on GOV.UK Prototype Kit v13 &middot; Powered by Claude</footer>

<script>
  document.getElementById('pdf').addEventListener('change', function() {
    document.getElementById('fileName').textContent = this.files[0] ? this.files[0].name : 'No file chosen';
  });

  // Step state helpers
  function setStep(stepId, iconId, state) {
    const li = document.getElementById(stepId);
    const icon = document.getElementById(iconId);
    li.className = state;
    if (state === 'active') icon.textContent = '●';
    else if (state === 'done') icon.textContent = '✓';
    else icon.textContent = '–';
  }

  // Timed fake progress that advances through steps on a schedule
  // Real done only fires when server responds
  let progressTimer = null;

  function startFakeProgress() {
    const bar = document.getElementById('progressBar');
    const steps = [
      { stepId: 'step-claude',  iconId: 'icon-claude',  delay: 0,     pct: 15 },
      { stepId: 'step-github',  iconId: 'icon-github',  delay: 18000, pct: 45 },
      { stepId: 'step-render',  iconId: 'icon-render',  delay: 30000, pct: 65 },
      { stepId: 'step-deploy',  iconId: 'icon-deploy',  delay: 45000, pct: 80 }
    ];

    let prevStepId = null, prevIconId = null;
    steps.forEach(function(s) {
      const t = setTimeout(function() {
        if (prevStepId) setStep(prevStepId, prevIconId, 'done');
        setStep(s.stepId, s.iconId, 'active');
        bar.style.width = s.pct + '%';
        prevStepId = s.stepId;
        prevIconId = s.iconId;
      }, s.delay);
      if (!progressTimer) progressTimer = [];
      progressTimer.push(t);
    });
  }

  function stopFakeProgress() {
    if (progressTimer) progressTimer.forEach(clearTimeout);
    progressTimer = null;
  }

  document.getElementById('generateForm').addEventListener('submit', async function(e) {
    e.preventDefault();

    const btn = document.getElementById('generateBtn');
    const btnText = document.getElementById('btnText');
    const btnArrow = document.getElementById('btnArrow');
    const progressPanel = document.getElementById('progressPanel');
    const donePanel = document.getElementById('donePanel');
    const errorPanel = document.getElementById('errorPanel');
    const bar = document.getElementById('progressBar');

    // Reset UI
    donePanel.className = 'done-panel';
    errorPanel.className = 'error-panel';
    progressPanel.className = 'progress-panel visible';
    bar.style.width = '5%';
    bar.className = 'progress-bar-fill';
    ['step-claude','step-github','step-render','step-deploy'].forEach(function(id) {
      document.getElementById(id).className = '';
      const iconId = 'icon-' + id.replace('step-', '');
      document.getElementById(iconId).textContent = '–';
    });

    btn.disabled = true;
    btnArrow.style.display = 'none';
    btnText.innerHTML = '<span class="spinner"></span> Generating&hellip;';

    startFakeProgress();

    try {
      const formData = new FormData(this);
      const response = await fetch('/generate', { method: 'POST', body: formData });

      stopFakeProgress();

      if (!response.ok) {
        const err = await response.json().catch(function() { return { error: 'Unknown error' }; });
        throw new Error(err.error || 'Something went wrong');
      }

      const result = await response.json();

      // All steps done
      bar.style.width = '100%';
      bar.className = 'progress-bar-fill complete';
      ['step-claude','step-github','step-render','step-deploy'].forEach(function(id) {
        setStep(id, 'icon-' + id.replace('step-', ''), 'done');
      });

      // Show done panel
      progressPanel.className = 'progress-panel';
      document.getElementById('openProtoBtn').href = result.url;
      donePanel.className = 'done-panel visible';

    } catch (err) {
      stopFakeProgress();
      progressPanel.className = 'progress-panel';
      document.getElementById('errorMsg').textContent = err.message || 'Try again or simplify your brief.';
      errorPanel.className = 'error-panel visible';
    }

    btn.disabled = false;
    btnArrow.style.display = '';
    btnText.textContent = 'Generate prototype';
  });
</script>
</body>
</html>`);
});

// ─── Generate endpoint ────────────────────────────────────────────────────────

app.post('/generate', upload.single('pdf'), async (req, res) => {
  try {
    const { brief, url } = req.body;
    const apiKey = process.env.ANTHROPIC_API_KEY;
    const githubToken = process.env.GITHUB_TOKEN;
    const renderApiKey = process.env.RENDER_API_KEY;
    const renderOwnerId = process.env.RENDER_OWNER_ID;
    const githubUsername = process.env.GITHUB_USERNAME;

    if (!apiKey) return res.status(500).json({ error: 'ANTHROPIC_API_KEY not set' });
    if (!githubToken) return res.status(500).json({ error: 'GITHUB_TOKEN not set' });
    if (!renderApiKey) return res.status(500).json({ error: 'RENDER_API_KEY not set' });
    if (!renderOwnerId) return res.status(500).json({ error: 'RENDER_OWNER_ID not set' });
    if (!githubUsername) return res.status(500).json({ error: 'GITHUB_USERNAME not set' });
    if (!brief || brief.trim().length < 5) return res.status(400).json({ error: 'Please describe your service' });

    // Step 1: Claude
    let userMessage = `Brief: ${brief.trim()}`;
    if (req.file) {
      try {
        const pdfData = await pdfParse(req.file.buffer);
        userMessage += `\n\nAdditional context from PDF:\n${pdfData.text.slice(0, 3000)}`;
      } catch (e) {}
    }
    if (url && url.trim()) userMessage += `\n\nReference URL: ${url.trim()}`;
    userMessage += '\n\nReturn only the JSON object. No explanation. No markdown.';

    const claudeResponse = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 4000,
        system: gdsPrompt,
        messages: [{ role: 'user', content: userMessage }]
      })
    });

    if (!claudeResponse.ok) {
      const err = await claudeResponse.json();
      throw new Error(err.error?.message || 'Claude API error');
    }

    const claudeData = await claudeResponse.json();
    const rawText = claudeData.content[0].text.trim();

    let spec;
    try {
      const clean = rawText.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/```\s*$/i, '').trim();
      spec = JSON.parse(clean);
    } catch (e) {
      throw new Error('Claude returned invalid JSON. Try simplifying your brief.');
    }

    if (!spec.serviceName || !spec.questions || spec.questions.length < 1) {
      throw new Error('Prototype spec incomplete. Try again.');
    }

    // Step 2: Build and push to GitHub
    const files = buildPrototypeFiles(spec);
    const timestamp = Date.now();
    const repoName = `prototype-${timestamp}`;

    await createGitHubRepo(repoName, githubToken);
    await pushAllFiles(githubUsername, repoName, files, githubToken);

    const repoUrl = `https://github.com/${githubUsername}/${repoName}`;

    // Step 3: Create Render service
    const serviceName = `prototype-${timestamp}`;
    const renderData = await createRenderService(repoUrl, serviceName, renderApiKey, renderOwnerId);

    const serviceId = renderData.service?.id;
    if (!serviceId) throw new Error('Render did not return a service ID');

    // Step 4: Poll until actually live
    const protoUrl = `https://${serviceName}.onrender.com`;
    await pollUntilLive(protoUrl);

    // Log it (fire and forget)
    appendToLog({
      serviceName: spec.serviceName,
      brief: brief.trim().slice(0, 120),
      url: protoUrl,
      repoUrl,
      createdAt: new Date().toISOString()
    }, githubUsername, githubToken).catch(e => console.error('Log write failed:', e));

    res.json({ url: protoUrl, repoUrl });

  } catch (err) {
    console.error(err);
    if (!res.headersSent) res.status(500).json({ error: err.message });
  }
});

// ─── Prototypes log page ──────────────────────────────────────────────────────

app.get('/prototypes', async (req, res) => {
  const githubToken = process.env.GITHUB_TOKEN;
  const githubUsername = process.env.GITHUB_USERNAME;
  const log = await getLog(githubUsername, githubToken);

  function timeAgo(iso) {
    const diff = Date.now() - new Date(iso).getTime();
    const mins = Math.floor(diff / 60000);
    const hours = Math.floor(diff / 3600000);
    const days = Math.floor(diff / 86400000);
    if (mins < 2) return 'just now';
    if (mins < 60) return mins + ' minutes ago';
    if (hours < 24) return hours + ' hour' + (hours > 1 ? 's' : '') + ' ago';
    return days + ' day' + (days > 1 ? 's' : '') + ' ago';
  }

  const rows = log.length === 0
    ? '<tr><td colspan="3" style="padding:30px 0;color:#505a5f;font-size:16px;">No prototypes generated yet.</td></tr>'
    : log.map(function(entry) {
        return '<tr>' +
          '<td style="font-size:19px;font-weight:700;color:#0b0c0c;">' + entry.serviceName + '</td>' +
          '<td style="white-space:nowrap;color:#505a5f;font-size:16px;padding-right:24px;">' + timeAgo(entry.createdAt) + '</td>' +
          '<td style="white-space:nowrap;"><a href="' + entry.url + '" target="_blank" rel="noopener" style="font-size:16px;color:#1d70b8;font-weight:700;">Open →</a></td>' +
          '</tr>';
      }).join('');

  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>All prototypes — GOV.UK Prototype Engine</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Inter', arial, sans-serif; background: #f3f2f1; min-height: 100vh; display: flex; flex-direction: column; }
    .govuk-header { background: #0b0c0c; padding: 12px 0; border-bottom: 10px solid #1d70b8; }
    .govuk-header__inner { max-width: 960px; margin: 0 auto; padding: 0 30px; display: flex; align-items: center; gap: 20px; }
    .govuk-header__crown { display: flex; align-items: center; gap: 10px; color: white; text-decoration: none; }
    .crown-svg { width: 36px; height: 32px; fill: white; }
    .govuk-header__logotype-text { font-size: 30px; font-weight: 700; color: white; letter-spacing: -1px; }
    .govuk-header__service-name { color: white; font-size: 16px; font-weight: 400; border-left: 1px solid #626a6e; padding-left: 20px; margin-left: 10px; }
    main { max-width: 960px; margin: 0 auto; padding: 48px 30px 80px; flex: 1; width: 100%; }
    .page-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 32px; flex-wrap: wrap; gap: 16px; }
    .page-header-left h1 { font-size: 32px; font-weight: 700; color: #0b0c0c; letter-spacing: -0.5px; }
    .page-header-left p { font-size: 14px; color: #6f777b; margin-top: 4px; font-weight: 500; }
    .new-btn { background: #00703c; color: white; text-decoration: none; padding: 11px 20px; font-size: 15px; font-weight: 600; font-family: inherit; border-radius: 4px; white-space: nowrap; }
    .new-btn:hover { background: #005a30; }
    .proto-list { display: flex; flex-direction: column; gap: 1px; background: #d8dde0; border: 1px solid #d8dde0; border-radius: 6px; overflow: hidden; }
    .proto-card { background: white; padding: 20px 24px; display: flex; align-items: center; justify-content: space-between; gap: 24px; transition: background 0.1s; }
    .proto-card:hover { background: #f8f8f8; }
    .proto-card-left { flex: 1; min-width: 0; }
    .proto-name { font-size: 17px; font-weight: 600; color: #0b0c0c; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
    .proto-meta { font-size: 13px; color: #6f777b; margin-top: 3px; font-weight: 400; }
    .proto-card-right { flex-shrink: 0; }
    .open-link { display: inline-flex; align-items: center; gap: 6px; background: #1d70b8; color: white; text-decoration: none; padding: 8px 16px; font-size: 14px; font-weight: 600; font-family: inherit; border-radius: 4px; }
    .open-link:hover { background: #003078; }
    .empty-state { background: white; border: 1px solid #d8dde0; border-radius: 6px; padding: 60px 30px; text-align: center; color: #6f777b; font-size: 16px; }
    footer { background: #0b0c0c; padding: 20px 30px; color: #6f777b; font-size: 13px; text-align: center; margin-top: auto; }
  </style>
</head>
<body>
<header class="govuk-header">
  <div class="govuk-header__inner">
    <a href="/" class="govuk-header__crown">
      <svg class="crown-svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 132 97" focusable="false">
        <path d="M25 30.2c3.5 1.5 7.7-.2 9.1-3.7 1.5-3.6-.2-7.8-3.9-9.2-3.6-1.4-7.6.3-9.1 3.9-1.4 3.5.3 7.5 3.9 9zM9 39.5c3.6 1.5 7.8-.2 9.2-3.7 1.5-3.6-.3-7.8-3.9-9.1-3.6-1.5-7.6.2-9.1 3.8-1.4 3.5.3 7.5 3.8 9zM4.4 57.2c3.5 1.5 7.7-.2 9.1-3.8 1.5-3.6-.2-7.7-3.9-9.1-3.5-1.5-7.6.3-9.1 3.8-1.4 3.5.3 7.6 3.9 9.1zm38.3-21.4c3.5 1.5 7.7-.2 9.1-3.8 1.5-3.6-.2-7.7-3.9-9.1-3.6-1.5-7.6.3-9.1 3.8-1.3 3.6.4 7.7 3.9 9.1zm64.4-5.6c-3.6 1.5-7.8-.2-9.1-3.7-1.5-3.6.2-7.8 3.8-9.2 3.6-1.4 7.7.3 9.2 3.9 1.3 3.5-.4 7.5-3.9 9zm15.9 9.3c-3.6 1.5-7.7-.2-9.1-3.7-1.5-3.6.2-7.8 3.7-9.1 3.6-1.5 7.7.2 9.2 3.8 1.5 3.5-.3 7.5-3.8 9zm4.7 17.7c-3.6 1.5-7.8-.2-9.2-3.8-1.5-3.6.2-7.7 3.9-9.1 3.6-1.5 7.7.3 9.2 3.8 1.3 3.5-.4 7.6-3.9 9.1zM89.3 35.8c-3.6 1.5-7.8-.2-9.2-3.8-1.4-3.6.2-7.7 3.9-9.1 3.6-1.5 7.7.3 9.2 3.8 1.4 3.6-.3 7.7-3.9 9.1zM69.7 17.7l8.9 4.7V9.3l-8.9 2.8c-.2-.3-.5-.6-.9-.9L72.4 0H59.6l3.5 11.2c-.3.3-.6.5-.9.9l-8.8-2.8v13.1l8.8-4.7c.3.3.6.7.9.9l-5 15.4v.1h14.2v-.1l-5-15.4c.4-.2.7-.6 1-.9zM66 92.8c16.9 0 32.8 1.1 47.1 3.2 4-16.9 8.9-26.7 14-33.5l-9.6-3.4c1 4.9 1.1 7.2 0 10.2-1.5-1.4-3-4.3-4.2-8.7L108.6 76c2.8-2 5-3.2 7.5-3.3-4.4 9.4-10 11.9-13.6 11.2-4.3-.8-6.3-4.6-5.6-7.9 1-4.7 5.7-5.9 8-.5 4.3-8.7-3-11.4-7.6-8.8 7.1-7.2 7.9-13.5 2.1-21.1-8 6.1-8.1 12.3-4.5 20.8-4.7-5.4-12.1-2.5-9.5 6.2 3.4-5.2 7.9-2 7.2 3.1-.6 4.3-6.4 7.8-13.5 7.2-10.3-.9-10.9-8-11.2-13.8 2.5-.5 7.1 1.8 11 7.3L80.2 60c-4.1 4.4-8 5.3-12.3 5.4 1.4-4.4 8-11.6 8-11.6H55.5s6.4 7.2 7.9 11.6c-4.2-.1-8-1-12.3-5.4l1.4 16.4c3.9-5.5 8.5-7.7 10.9-7.3-.3 5.8-.9 12.8-11.1 13.8-7.2.6-12.9-2.9-13.5-7.2-.7-5 3.8-8.3 7.1-3.1 2.7-8.7-4.6-11.6-9.4-6.2 3.7-8.5 3.6-14.7-4.6-20.8-5.8 7.6-5 13.9 2.2 21.1-4.7-2.6-11.9.1-7.7 8.8 2.3-5.5 7.1-4.2 8.1.5.7 3.3-1.3 7.1-5.7 7.9-3.5.7-9-1.8-13.5-11.2 2.5.1 4.7 1.3 7.5 3.3l-4.7-15.4c-1.2 4.4-2.7 7.2-4.3 8.7-1.1-3-.9-5.3 0-10.2l-9.5 3.4c5 6.9 9.9 16.7 14 33.5 14.8-2.1 30.8-3.2 47.7-3.2z"/>
      </svg>
      <span class="govuk-header__logotype-text">GOV.UK</span>
    </a>
    <span class="govuk-header__service-name">Prototype Engine</span>
  </div>
</header>
<main>
  <div class="page-header">
    <div class="page-header-left">
      <h1>All prototypes</h1>
      <p>${log.length} generated</p>
    </div>
    <a href="/" class="new-btn">+ New prototype</a>
  </div>
  ${log.length === 0
    ? '<div class="empty-state">No prototypes generated yet.</div>'
    : '<div class="proto-list">' + log.map(function(entry) {
        return '<div class="proto-card">' +
          '<div class="proto-card-left">' +
            '<div class="proto-name">' + entry.serviceName + '</div>' +
            '<div class="proto-meta">' + timeAgo(entry.createdAt) + '</div>' +
          '</div>' +
          '<div class="proto-card-right">' +
            '<a href="' + entry.url + '" target="_blank" rel="noopener" class="open-link">Open prototype</a>' +
          '</div>' +
        '</div>';
      }).join('') + '</div>'
  }
</main>
<footer>GOV.UK Prototype Kit v13 &middot; Powered by Claude Sonnet</footer>
</body>
</html>`);
});

const port = process.env.PORT || 3000;
app.listen(port, () => console.log(`Prototype Engine running on port ${port}`));
